// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	PutMessageRequest
	PutMessageResponse
	PatchMessageRequest
	PatchMessageResponse
	DeleteMessageRequest
	DeleteMessageResponse
	PullChatMessagesRequest
	PullChatMessagesResponse
	PutReadAudioRequest
	PutReadAudioResponse
	PushReadAudioNotice
	PullReadAudioStatusRequest
	PullReadAudioStatusResponse
	PushReadMessagesNotice
	PutReadMessagesRequest
	PutReadMessagesResponse
	PutMessageReadSateNotice
	PutChatReadPositionNotice
	ReadCountNotification
	PushMessageReadCountNotice
	PullMessageReadStateRequest
	PullMessageReadStateResponse
	PullMessageIReadStateRequest
	PullMessageIReadStateResponse
	PullMessageMeReadStateRequest
	PullMessageMeReadStateResponse
	PushMessagesRequest
	PushMessagesResponse
	PullMessagesByIdsRequest
	PullMessagesByIdsResponse
	PullMessagesByPositionsRequest
	PullMessagesByPositionsResponse
	PutTransmitMessageRequest
	PutTransmitMessageResponse
	PullUnreadAtMessageIdsRequest
	PullUnreadAtMessageIdsResponse
	PutCopyMessagesRequest
	PutCopyMessagesResponse
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entities "git.byted.org/ee/lark/im-protobuf/improto/entities"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PullChatMessagesRequest_Type int32

const (
	PullChatMessagesRequest_BEFORE PullChatMessagesRequest_Type = 1
	PullChatMessagesRequest_AFTER  PullChatMessagesRequest_Type = 2
	PullChatMessagesRequest_LATEST PullChatMessagesRequest_Type = 3
)

var PullChatMessagesRequest_Type_name = map[int32]string{
	1: "BEFORE",
	2: "AFTER",
	3: "LATEST",
}
var PullChatMessagesRequest_Type_value = map[string]int32{
	"BEFORE": 1,
	"AFTER":  2,
	"LATEST": 3,
}

func (x PullChatMessagesRequest_Type) Enum() *PullChatMessagesRequest_Type {
	p := new(PullChatMessagesRequest_Type)
	*p = x
	return p
}
func (x PullChatMessagesRequest_Type) String() string {
	return proto.EnumName(PullChatMessagesRequest_Type_name, int32(x))
}
func (x *PullChatMessagesRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PullChatMessagesRequest_Type_value, data, "PullChatMessagesRequest_Type")
	if err != nil {
		return err
	}
	*x = PullChatMessagesRequest_Type(value)
	return nil
}
func (PullChatMessagesRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

// 发表消息接口
type PutMessageRequest struct {
	Type             *entities.Message_Type     `protobuf:"varint,1,opt,name=type,enum=Message_Type" json:"type,omitempty"`
	Content          *PutMessageRequest_Content `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	ChatId           *string                    `protobuf:"bytes,3,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	RootId           *string                    `protobuf:"bytes,4,opt,name=root_id,json=rootId" json:"root_id,omitempty"`
	ParentId         *string                    `protobuf:"bytes,5,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Cid              *string                    `protobuf:"bytes,6,opt,name=cid" json:"cid,omitempty"`
	IsNotified       *bool                      `protobuf:"varint,7,opt,name=is_notified,json=isNotified,def=1" json:"is_notified,omitempty"`
	SendToChat       *bool                      `protobuf:"varint,8,opt,name=send_to_chat,json=sendToChat,def=1" json:"send_to_chat,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *PutMessageRequest) Reset()                    { *m = PutMessageRequest{} }
func (m *PutMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*PutMessageRequest) ProtoMessage()               {}
func (*PutMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_PutMessageRequest_IsNotified bool = true
const Default_PutMessageRequest_SendToChat bool = true

func (m *PutMessageRequest) GetType() entities.Message_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return entities.Message_POST
}

func (m *PutMessageRequest) GetContent() *PutMessageRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PutMessageRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutMessageRequest) GetRootId() string {
	if m != nil && m.RootId != nil {
		return *m.RootId
	}
	return ""
}

func (m *PutMessageRequest) GetParentId() string {
	if m != nil && m.ParentId != nil {
		return *m.ParentId
	}
	return ""
}

func (m *PutMessageRequest) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

func (m *PutMessageRequest) GetIsNotified() bool {
	if m != nil && m.IsNotified != nil {
		return *m.IsNotified
	}
	return Default_PutMessageRequest_IsNotified
}

func (m *PutMessageRequest) GetSendToChat() bool {
	if m != nil && m.SendToChat != nil {
		return *m.SendToChat
	}
	return Default_PutMessageRequest_SendToChat
}

type PutMessageRequest_Content struct {
	// 文本消息相关
	Text *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	// 图片信息相关
	ImageKey *string `protobuf:"bytes,2,opt,name=image_key,json=imageKey" json:"image_key,omitempty"`
	// 帖子相关
	Title       *string  `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Attachments []string `protobuf:"bytes,4,rep,name=attachments" json:"attachments,omitempty"`
	IsNotified  *bool    `protobuf:"varint,5,opt,name=is_notified,json=isNotified" json:"is_notified,omitempty"`
	FileKey     *string  `protobuf:"bytes,6,opt,name=file_key,json=fileKey" json:"file_key,omitempty"`
	// 语音消息相关
	AudioKey         *string `protobuf:"bytes,7,opt,name=audio_key,json=audioKey" json:"audio_key,omitempty"`
	AudioDuration    *int32  `protobuf:"varint,8,opt,name=audio_duration,json=audioDuration" json:"audio_duration,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutMessageRequest_Content) Reset()                    { *m = PutMessageRequest_Content{} }
func (m *PutMessageRequest_Content) String() string            { return proto.CompactTextString(m) }
func (*PutMessageRequest_Content) ProtoMessage()               {}
func (*PutMessageRequest_Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *PutMessageRequest_Content) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *PutMessageRequest_Content) GetImageKey() string {
	if m != nil && m.ImageKey != nil {
		return *m.ImageKey
	}
	return ""
}

func (m *PutMessageRequest_Content) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *PutMessageRequest_Content) GetAttachments() []string {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *PutMessageRequest_Content) GetIsNotified() bool {
	if m != nil && m.IsNotified != nil {
		return *m.IsNotified
	}
	return false
}

func (m *PutMessageRequest_Content) GetFileKey() string {
	if m != nil && m.FileKey != nil {
		return *m.FileKey
	}
	return ""
}

func (m *PutMessageRequest_Content) GetAudioKey() string {
	if m != nil && m.AudioKey != nil {
		return *m.AudioKey
	}
	return ""
}

func (m *PutMessageRequest_Content) GetAudioDuration() int32 {
	if m != nil && m.AudioDuration != nil {
		return *m.AudioDuration
	}
	return 0
}

type PutMessageResponse struct {
	Message          *entities.Message `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	Positions        map[string]int32  `protobuf:"bytes,2,rep,name=positions" json:"positions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PutMessageResponse) Reset()                    { *m = PutMessageResponse{} }
func (m *PutMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*PutMessageResponse) ProtoMessage()               {}
func (*PutMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutMessageResponse) GetMessage() *entities.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PutMessageResponse) GetPositions() map[string]int32 {
	if m != nil {
		return m.Positions
	}
	return nil
}

// 修改消息
type PatchMessageRequest struct {
	Content          *PatchMessageRequest_Content `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	Id               *string                      `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PatchMessageRequest) Reset()                    { *m = PatchMessageRequest{} }
func (m *PatchMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchMessageRequest) ProtoMessage()               {}
func (*PatchMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PatchMessageRequest) GetContent() *PatchMessageRequest_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PatchMessageRequest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type PatchMessageRequest_Content struct {
	Text             *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Title            *string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PatchMessageRequest_Content) Reset()                    { *m = PatchMessageRequest_Content{} }
func (m *PatchMessageRequest_Content) String() string            { return proto.CompactTextString(m) }
func (*PatchMessageRequest_Content) ProtoMessage()               {}
func (*PatchMessageRequest_Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *PatchMessageRequest_Content) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *PatchMessageRequest_Content) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type PatchMessageResponse struct {
	Message          *entities.Message `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PatchMessageResponse) Reset()                    { *m = PatchMessageResponse{} }
func (m *PatchMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*PatchMessageResponse) ProtoMessage()               {}
func (*PatchMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PatchMessageResponse) GetMessage() *entities.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

// 删除消息
type DeleteMessageRequest struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteMessageRequest) Reset()                    { *m = DeleteMessageRequest{} }
func (m *DeleteMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteMessageRequest) ProtoMessage()               {}
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteMessageRequest) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type DeleteMessageResponse struct {
	Message          *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteMessageResponse) Reset()                    { *m = DeleteMessageResponse{} }
func (m *DeleteMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteMessageResponse) ProtoMessage()               {}
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteMessageResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

// 获取消息接口
type PullChatMessagesRequest struct {
	ChatId           *string                       `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Position         *int32                        `protobuf:"varint,2,opt,name=position,def=0" json:"position,omitempty"`
	Count            *int32                        `protobuf:"varint,3,opt,name=count,def=20" json:"count,omitempty"`
	Type             *PullChatMessagesRequest_Type `protobuf:"varint,4,req,name=type,enum=PullChatMessagesRequest_Type,def=3" json:"type,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PullChatMessagesRequest) Reset()                    { *m = PullChatMessagesRequest{} }
func (m *PullChatMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*PullChatMessagesRequest) ProtoMessage()               {}
func (*PullChatMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_PullChatMessagesRequest_Position int32 = 0
const Default_PullChatMessagesRequest_Count int32 = 20
const Default_PullChatMessagesRequest_Type PullChatMessagesRequest_Type = PullChatMessagesRequest_LATEST

func (m *PullChatMessagesRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PullChatMessagesRequest) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return Default_PullChatMessagesRequest_Position
}

func (m *PullChatMessagesRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_PullChatMessagesRequest_Count
}

func (m *PullChatMessagesRequest) GetType() PullChatMessagesRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_PullChatMessagesRequest_Type
}

type PullChatMessagesResponse struct {
	Messages         map[string]*entities.Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PullChatMessagesResponse) Reset()                    { *m = PullChatMessagesResponse{} }
func (m *PullChatMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*PullChatMessagesResponse) ProtoMessage()               {}
func (*PullChatMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PullChatMessagesResponse) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// ---- 语音消息 已播放相关-----
// 客户端播放语音后通知服务器已收听此语音
type PutReadAudioRequest struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutReadAudioRequest) Reset()                    { *m = PutReadAudioRequest{} }
func (m *PutReadAudioRequest) String() string            { return proto.CompactTextString(m) }
func (*PutReadAudioRequest) ProtoMessage()               {}
func (*PutReadAudioRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PutReadAudioRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutReadAudioRequest) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

// 对应Request的回复
type PutReadAudioResponse struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutReadAudioResponse) Reset()                    { *m = PutReadAudioResponse{} }
func (m *PutReadAudioResponse) String() string            { return proto.CompactTextString(m) }
func (*PutReadAudioResponse) ProtoMessage()               {}
func (*PutReadAudioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PutReadAudioResponse) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutReadAudioResponse) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

// 同一用户在一台设备上收听了某条语音，会推送该消息到该用户的其他设备，用于同步语音收听情况。
type PushReadAudioNotice struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushReadAudioNotice) Reset()                    { *m = PushReadAudioNotice{} }
func (m *PushReadAudioNotice) String() string            { return proto.CompactTextString(m) }
func (*PushReadAudioNotice) ProtoMessage()               {}
func (*PushReadAudioNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PushReadAudioNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushReadAudioNotice) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

// 获取音频已播状态请求
type PullReadAudioStatusRequest struct {
	Pairs            []*PullReadAudioStatusRequest_Pair `protobuf:"bytes,1,rep,name=pairs" json:"pairs,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *PullReadAudioStatusRequest) Reset()                    { *m = PullReadAudioStatusRequest{} }
func (m *PullReadAudioStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*PullReadAudioStatusRequest) ProtoMessage()               {}
func (*PullReadAudioStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PullReadAudioStatusRequest) GetPairs() []*PullReadAudioStatusRequest_Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type PullReadAudioStatusRequest_Pair struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PullReadAudioStatusRequest_Pair) Reset()         { *m = PullReadAudioStatusRequest_Pair{} }
func (m *PullReadAudioStatusRequest_Pair) String() string { return proto.CompactTextString(m) }
func (*PullReadAudioStatusRequest_Pair) ProtoMessage()    {}
func (*PullReadAudioStatusRequest_Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

func (m *PullReadAudioStatusRequest_Pair) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PullReadAudioStatusRequest_Pair) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

// 获取音频已播状态返回
type PullReadAudioStatusResponse struct {
	Pairs            []*PullReadAudioStatusResponse_Pair `protobuf:"bytes,1,rep,name=pairs" json:"pairs,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *PullReadAudioStatusResponse) Reset()                    { *m = PullReadAudioStatusResponse{} }
func (m *PullReadAudioStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*PullReadAudioStatusResponse) ProtoMessage()               {}
func (*PullReadAudioStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PullReadAudioStatusResponse) GetPairs() []*PullReadAudioStatusResponse_Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type PullReadAudioStatusResponse_Pair struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	IsRead           *bool   `protobuf:"varint,3,opt,name=is_read,json=isRead" json:"is_read,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PullReadAudioStatusResponse_Pair) Reset()         { *m = PullReadAudioStatusResponse_Pair{} }
func (m *PullReadAudioStatusResponse_Pair) String() string { return proto.CompactTextString(m) }
func (*PullReadAudioStatusResponse_Pair) ProtoMessage()    {}
func (*PullReadAudioStatusResponse_Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

func (m *PullReadAudioStatusResponse_Pair) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PullReadAudioStatusResponse_Pair) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *PullReadAudioStatusResponse_Pair) GetIsRead() bool {
	if m != nil && m.IsRead != nil {
		return *m.IsRead
	}
	return false
}

// ---- 已读未读 API 相关 -----
// [逐渐废弃] 命名不符合规范 读消息信息回传服务端
type PushReadMessagesNotice struct {
	ChatId           *string  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageIds       []string `protobuf:"bytes,2,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	Position         *int32   `protobuf:"varint,3,opt,name=position,def=-1" json:"position,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PushReadMessagesNotice) Reset()                    { *m = PushReadMessagesNotice{} }
func (m *PushReadMessagesNotice) String() string            { return proto.CompactTextString(m) }
func (*PushReadMessagesNotice) ProtoMessage()               {}
func (*PushReadMessagesNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

const Default_PushReadMessagesNotice_Position int32 = -1

func (m *PushReadMessagesNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushReadMessagesNotice) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PushReadMessagesNotice) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return Default_PushReadMessagesNotice_Position
}

// 读消息信息回传服务端 new 对应 PUT_READ_MESSAGES
type PutReadMessagesRequest struct {
	ChatId           *string  `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageIds       []string `protobuf:"bytes,2,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	MaxPosition      *int32   `protobuf:"varint,3,req,name=max_position,json=maxPosition,def=-1" json:"max_position,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PutReadMessagesRequest) Reset()                    { *m = PutReadMessagesRequest{} }
func (m *PutReadMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*PutReadMessagesRequest) ProtoMessage()               {}
func (*PutReadMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

const Default_PutReadMessagesRequest_MaxPosition int32 = -1

func (m *PutReadMessagesRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutReadMessagesRequest) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PutReadMessagesRequest) GetMaxPosition() int32 {
	if m != nil && m.MaxPosition != nil {
		return *m.MaxPosition
	}
	return Default_PutReadMessagesRequest_MaxPosition
}

type PutReadMessagesResponse struct {
	LastMessagePosition *int32 `protobuf:"varint,1,opt,name=last_message_position,json=lastMessagePosition" json:"last_message_position,omitempty"`
	NewMessageCount     *int32 `protobuf:"varint,2,opt,name=new_message_count,json=newMessageCount" json:"new_message_count,omitempty"`
	XXX_unrecognized    []byte `json:"-"`
}

func (m *PutReadMessagesResponse) Reset()                    { *m = PutReadMessagesResponse{} }
func (m *PutReadMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*PutReadMessagesResponse) ProtoMessage()               {}
func (*PutReadMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PutReadMessagesResponse) GetLastMessagePosition() int32 {
	if m != nil && m.LastMessagePosition != nil {
		return *m.LastMessagePosition
	}
	return 0
}

func (m *PutReadMessagesResponse) GetNewMessageCount() int32 {
	if m != nil && m.NewMessageCount != nil {
		return *m.NewMessageCount
	}
	return 0
}

// [废弃] 更新会话中多条消息的已读状态
type PutMessageReadSateNotice struct {
	ChatId           *string  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageIds       []string `protobuf:"bytes,2,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PutMessageReadSateNotice) Reset()                    { *m = PutMessageReadSateNotice{} }
func (m *PutMessageReadSateNotice) String() string            { return proto.CompactTextString(m) }
func (*PutMessageReadSateNotice) ProtoMessage()               {}
func (*PutMessageReadSateNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PutMessageReadSateNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutMessageReadSateNotice) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

// [废弃] 更新会话中消息已读的最大位置
type PutChatReadPositionNotice struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Position         *int32  `protobuf:"varint,2,opt,name=position" json:"position,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutChatReadPositionNotice) Reset()                    { *m = PutChatReadPositionNotice{} }
func (m *PutChatReadPositionNotice) String() string            { return proto.CompactTextString(m) }
func (*PutChatReadPositionNotice) ProtoMessage()               {}
func (*PutChatReadPositionNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PutChatReadPositionNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutChatReadPositionNotice) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

// [逐渐废弃] 命名不符合规范 服务端下发已读状态
type ReadCountNotification struct {
	Pairs            []*ReadCountNotification_Pair `protobuf:"bytes,1,rep,name=pairs" json:"pairs,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ReadCountNotification) Reset()                    { *m = ReadCountNotification{} }
func (m *ReadCountNotification) String() string            { return proto.CompactTextString(m) }
func (*ReadCountNotification) ProtoMessage()               {}
func (*ReadCountNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ReadCountNotification) GetPairs() []*ReadCountNotification_Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type ReadCountNotification_Pair struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	Count            *int32  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadCountNotification_Pair) Reset()                    { *m = ReadCountNotification_Pair{} }
func (m *ReadCountNotification_Pair) String() string            { return proto.CompactTextString(m) }
func (*ReadCountNotification_Pair) ProtoMessage()               {}
func (*ReadCountNotification_Pair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18, 0} }

func (m *ReadCountNotification_Pair) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *ReadCountNotification_Pair) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *ReadCountNotification_Pair) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 服务端下发已读状态 new 对应 PUSH_MESSAGE_READ_COUNT
type PushMessageReadCountNotice struct {
	Pairs            []*PushMessageReadCountNotice_Pair `protobuf:"bytes,1,rep,name=pairs" json:"pairs,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *PushMessageReadCountNotice) Reset()                    { *m = PushMessageReadCountNotice{} }
func (m *PushMessageReadCountNotice) String() string            { return proto.CompactTextString(m) }
func (*PushMessageReadCountNotice) ProtoMessage()               {}
func (*PushMessageReadCountNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PushMessageReadCountNotice) GetPairs() []*PushMessageReadCountNotice_Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type PushMessageReadCountNotice_Pair struct {
	ChatId           *string  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string  `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	Count            *int32   `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	ChatterIds       []string `protobuf:"bytes,4,rep,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
	UnreadCount      *int32   `protobuf:"varint,5,opt,name=unread_count,json=unreadCount" json:"unread_count,omitempty"`
	ReadCount        *int32   `protobuf:"varint,6,opt,name=read_count,json=readCount" json:"read_count,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PushMessageReadCountNotice_Pair) Reset()         { *m = PushMessageReadCountNotice_Pair{} }
func (m *PushMessageReadCountNotice_Pair) String() string { return proto.CompactTextString(m) }
func (*PushMessageReadCountNotice_Pair) ProtoMessage()    {}
func (*PushMessageReadCountNotice_Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19, 0}
}

func (m *PushMessageReadCountNotice_Pair) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushMessageReadCountNotice_Pair) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *PushMessageReadCountNotice_Pair) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *PushMessageReadCountNotice_Pair) GetChatterIds() []string {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

func (m *PushMessageReadCountNotice_Pair) GetUnreadCount() int32 {
	if m != nil && m.UnreadCount != nil {
		return *m.UnreadCount
	}
	return 0
}

func (m *PushMessageReadCountNotice_Pair) GetReadCount() int32 {
	if m != nil && m.ReadCount != nil {
		return *m.ReadCount
	}
	return 0
}

// 查看某条消息的已读未读状态, 只有消息的发送者可以调用
type PullMessageReadStateRequest struct {
	Pairs            []*PullMessageReadStateRequest_Pair `protobuf:"bytes,1,rep,name=pairs" json:"pairs,omitempty"`
	NeedUsers        *bool                               `protobuf:"varint,2,opt,name=need_users,json=needUsers,def=0" json:"need_users,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *PullMessageReadStateRequest) Reset()                    { *m = PullMessageReadStateRequest{} }
func (m *PullMessageReadStateRequest) String() string            { return proto.CompactTextString(m) }
func (*PullMessageReadStateRequest) ProtoMessage()               {}
func (*PullMessageReadStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

const Default_PullMessageReadStateRequest_NeedUsers bool = false

func (m *PullMessageReadStateRequest) GetPairs() []*PullMessageReadStateRequest_Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *PullMessageReadStateRequest) GetNeedUsers() bool {
	if m != nil && m.NeedUsers != nil {
		return *m.NeedUsers
	}
	return Default_PullMessageReadStateRequest_NeedUsers
}

type PullMessageReadStateRequest_Pair struct {
	ChatId           *string `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	MessageId        *string `protobuf:"bytes,2,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PullMessageReadStateRequest_Pair) Reset()         { *m = PullMessageReadStateRequest_Pair{} }
func (m *PullMessageReadStateRequest_Pair) String() string { return proto.CompactTextString(m) }
func (*PullMessageReadStateRequest_Pair) ProtoMessage()    {}
func (*PullMessageReadStateRequest_Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{20, 0}
}

func (m *PullMessageReadStateRequest_Pair) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PullMessageReadStateRequest_Pair) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

type PullMessageReadStateResponse struct {
	ReadStates       map[string]*PullMessageReadStateResponse_ReadState `protobuf:"bytes,1,rep,name=read_states,json=readStates" json:"read_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                                             `json:"-"`
}

func (m *PullMessageReadStateResponse) Reset()                    { *m = PullMessageReadStateResponse{} }
func (m *PullMessageReadStateResponse) String() string            { return proto.CompactTextString(m) }
func (*PullMessageReadStateResponse) ProtoMessage()               {}
func (*PullMessageReadStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PullMessageReadStateResponse) GetReadStates() map[string]*PullMessageReadStateResponse_ReadState {
	if m != nil {
		return m.ReadStates
	}
	return nil
}

type PullMessageReadStateResponse_ReadState struct {
	ReadUserIds      []string `protobuf:"bytes,1,rep,name=read_user_ids,json=readUserIds" json:"read_user_ids,omitempty"`
	UnreadUserIds    []string `protobuf:"bytes,2,rep,name=unread_user_ids,json=unreadUserIds" json:"unread_user_ids,omitempty"`
	UnreadCount      *int32   `protobuf:"varint,3,opt,name=unread_count,json=unreadCount" json:"unread_count,omitempty"`
	ReadCount        *int32   `protobuf:"varint,4,opt,name=read_count,json=readCount" json:"read_count,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullMessageReadStateResponse_ReadState) Reset() {
	*m = PullMessageReadStateResponse_ReadState{}
}
func (m *PullMessageReadStateResponse_ReadState) String() string { return proto.CompactTextString(m) }
func (*PullMessageReadStateResponse_ReadState) ProtoMessage()    {}
func (*PullMessageReadStateResponse_ReadState) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21, 0}
}

func (m *PullMessageReadStateResponse_ReadState) GetReadUserIds() []string {
	if m != nil {
		return m.ReadUserIds
	}
	return nil
}

func (m *PullMessageReadStateResponse_ReadState) GetUnreadUserIds() []string {
	if m != nil {
		return m.UnreadUserIds
	}
	return nil
}

func (m *PullMessageReadStateResponse_ReadState) GetUnreadCount() int32 {
	if m != nil && m.UnreadCount != nil {
		return *m.UnreadCount
	}
	return 0
}

func (m *PullMessageReadStateResponse_ReadState) GetReadCount() int32 {
	if m != nil && m.ReadCount != nil {
		return *m.ReadCount
	}
	return 0
}

// 查看某条消息自己是否已读，[废弃]
type PullMessageIReadStateRequest struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullMessageIReadStateRequest) Reset()                    { *m = PullMessageIReadStateRequest{} }
func (m *PullMessageIReadStateRequest) String() string            { return proto.CompactTextString(m) }
func (*PullMessageIReadStateRequest) ProtoMessage()               {}
func (*PullMessageIReadStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PullMessageIReadStateRequest) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

type PullMessageIReadStateResponse struct {
	ReadStatus       map[string]bool `protobuf:"bytes,1,rep,name=read_status,json=readStatus" json:"read_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PullMessageIReadStateResponse) Reset()                    { *m = PullMessageIReadStateResponse{} }
func (m *PullMessageIReadStateResponse) String() string            { return proto.CompactTextString(m) }
func (*PullMessageIReadStateResponse) ProtoMessage()               {}
func (*PullMessageIReadStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PullMessageIReadStateResponse) GetReadStatus() map[string]bool {
	if m != nil {
		return m.ReadStatus
	}
	return nil
}

// 查看某条消息自己是否已读，自动忽略不存在的 message_id
type PullMessageMeReadStateRequest struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullMessageMeReadStateRequest) Reset()                    { *m = PullMessageMeReadStateRequest{} }
func (m *PullMessageMeReadStateRequest) String() string            { return proto.CompactTextString(m) }
func (*PullMessageMeReadStateRequest) ProtoMessage()               {}
func (*PullMessageMeReadStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PullMessageMeReadStateRequest) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

type PullMessageMeReadStateResponse struct {
	ReadStatus       map[string]bool `protobuf:"bytes,1,rep,name=read_status,json=readStatus" json:"read_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PullMessageMeReadStateResponse) Reset()                    { *m = PullMessageMeReadStateResponse{} }
func (m *PullMessageMeReadStateResponse) String() string            { return proto.CompactTextString(m) }
func (*PullMessageMeReadStateResponse) ProtoMessage()               {}
func (*PullMessageMeReadStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PullMessageMeReadStateResponse) GetReadStatus() map[string]bool {
	if m != nil {
		return m.ReadStatus
	}
	return nil
}

// 下发消息
type PushMessagesRequest struct {
	Messages         map[string]*entities.Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Notices          map[string]*entities.Notice  `protobuf:"bytes,2,rep,name=notices" json:"notices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PushMessagesRequest) Reset()                    { *m = PushMessagesRequest{} }
func (m *PushMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*PushMessagesRequest) ProtoMessage()               {}
func (*PushMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PushMessagesRequest) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PushMessagesRequest) GetNotices() map[string]*entities.Notice {
	if m != nil {
		return m.Notices
	}
	return nil
}

type PushMessagesResponse struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PushMessagesResponse) Reset()                    { *m = PushMessagesResponse{} }
func (m *PushMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*PushMessagesResponse) ProtoMessage()               {}
func (*PushMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PushMessagesResponse) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

// 消息 mget
type PullMessagesByIdsRequest struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullMessagesByIdsRequest) Reset()                    { *m = PullMessagesByIdsRequest{} }
func (m *PullMessagesByIdsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullMessagesByIdsRequest) ProtoMessage()               {}
func (*PullMessagesByIdsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PullMessagesByIdsRequest) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

type PullMessagesByIdsResponse struct {
	Messages         map[string]*entities.Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PullMessagesByIdsResponse) Reset()                    { *m = PullMessagesByIdsResponse{} }
func (m *PullMessagesByIdsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullMessagesByIdsResponse) ProtoMessage()               {}
func (*PullMessagesByIdsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *PullMessagesByIdsResponse) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// 根据位置拉取消息
type PullMessagesByPositionsRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Positions        []int32 `protobuf:"varint,2,rep,name=positions" json:"positions,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PullMessagesByPositionsRequest) Reset()                    { *m = PullMessagesByPositionsRequest{} }
func (m *PullMessagesByPositionsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullMessagesByPositionsRequest) ProtoMessage()               {}
func (*PullMessagesByPositionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PullMessagesByPositionsRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PullMessagesByPositionsRequest) GetPositions() []int32 {
	if m != nil {
		return m.Positions
	}
	return nil
}

// map的key为position，value为消息实体，对于不合法的position将不出现在key中，也不返回消息实体
type PullMessagesByPositionsResponse struct {
	Messages         map[int32]*entities.Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PullMessagesByPositionsResponse) Reset()         { *m = PullMessagesByPositionsResponse{} }
func (m *PullMessagesByPositionsResponse) String() string { return proto.CompactTextString(m) }
func (*PullMessagesByPositionsResponse) ProtoMessage()    {}
func (*PullMessagesByPositionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{31}
}

func (m *PullMessagesByPositionsResponse) GetMessages() map[int32]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PutTransmitMessageRequest struct {
	ChatIds          []string          `protobuf:"bytes,1,rep,name=chat_ids,json=chatIds" json:"chat_ids,omitempty"`
	MessageId        *string           `protobuf:"bytes,2,req,name=message_id,json=messageId" json:"message_id,omitempty"`
	Cids             map[string]string `protobuf:"bytes,3,rep,name=cids" json:"cids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PutTransmitMessageRequest) Reset()                    { *m = PutTransmitMessageRequest{} }
func (m *PutTransmitMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*PutTransmitMessageRequest) ProtoMessage()               {}
func (*PutTransmitMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PutTransmitMessageRequest) GetChatIds() []string {
	if m != nil {
		return m.ChatIds
	}
	return nil
}

func (m *PutTransmitMessageRequest) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *PutTransmitMessageRequest) GetCids() map[string]string {
	if m != nil {
		return m.Cids
	}
	return nil
}

type PutTransmitMessageResponse struct {
	Messages         map[string]*entities.Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PutTransmitMessageResponse) Reset()                    { *m = PutTransmitMessageResponse{} }
func (m *PutTransmitMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*PutTransmitMessageResponse) ProtoMessage()               {}
func (*PutTransmitMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PutTransmitMessageResponse) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type PullUnreadAtMessageIdsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PullUnreadAtMessageIdsRequest) Reset()                    { *m = PullUnreadAtMessageIdsRequest{} }
func (m *PullUnreadAtMessageIdsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullUnreadAtMessageIdsRequest) ProtoMessage()               {}
func (*PullUnreadAtMessageIdsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

type PullUnreadAtMessageIdsResponse struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullUnreadAtMessageIdsResponse) Reset()                    { *m = PullUnreadAtMessageIdsResponse{} }
func (m *PullUnreadAtMessageIdsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullUnreadAtMessageIdsResponse) ProtoMessage()               {}
func (*PullUnreadAtMessageIdsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PullUnreadAtMessageIdsResponse) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

type PutCopyMessagesRequest struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	ToChatId         *string  `protobuf:"bytes,2,req,name=to_chat_id,json=toChatId" json:"to_chat_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PutCopyMessagesRequest) Reset()                    { *m = PutCopyMessagesRequest{} }
func (m *PutCopyMessagesRequest) String() string            { return proto.CompactTextString(m) }
func (*PutCopyMessagesRequest) ProtoMessage()               {}
func (*PutCopyMessagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PutCopyMessagesRequest) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PutCopyMessagesRequest) GetToChatId() string {
	if m != nil && m.ToChatId != nil {
		return *m.ToChatId
	}
	return ""
}

type PutCopyMessagesResponse struct {
	Messages         map[string]*entities.Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PutCopyMessagesResponse) Reset()                    { *m = PutCopyMessagesResponse{} }
func (m *PutCopyMessagesResponse) String() string            { return proto.CompactTextString(m) }
func (*PutCopyMessagesResponse) ProtoMessage()               {}
func (*PutCopyMessagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *PutCopyMessagesResponse) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*PutMessageRequest)(nil), "PutMessageRequest")
	proto.RegisterType((*PutMessageRequest_Content)(nil), "PutMessageRequest.Content")
	proto.RegisterType((*PutMessageResponse)(nil), "PutMessageResponse")
	proto.RegisterType((*PatchMessageRequest)(nil), "PatchMessageRequest")
	proto.RegisterType((*PatchMessageRequest_Content)(nil), "PatchMessageRequest.Content")
	proto.RegisterType((*PatchMessageResponse)(nil), "PatchMessageResponse")
	proto.RegisterType((*DeleteMessageRequest)(nil), "DeleteMessageRequest")
	proto.RegisterType((*DeleteMessageResponse)(nil), "DeleteMessageResponse")
	proto.RegisterType((*PullChatMessagesRequest)(nil), "PullChatMessagesRequest")
	proto.RegisterType((*PullChatMessagesResponse)(nil), "PullChatMessagesResponse")
	proto.RegisterType((*PutReadAudioRequest)(nil), "PutReadAudioRequest")
	proto.RegisterType((*PutReadAudioResponse)(nil), "PutReadAudioResponse")
	proto.RegisterType((*PushReadAudioNotice)(nil), "PushReadAudioNotice")
	proto.RegisterType((*PullReadAudioStatusRequest)(nil), "PullReadAudioStatusRequest")
	proto.RegisterType((*PullReadAudioStatusRequest_Pair)(nil), "PullReadAudioStatusRequest.Pair")
	proto.RegisterType((*PullReadAudioStatusResponse)(nil), "PullReadAudioStatusResponse")
	proto.RegisterType((*PullReadAudioStatusResponse_Pair)(nil), "PullReadAudioStatusResponse.Pair")
	proto.RegisterType((*PushReadMessagesNotice)(nil), "PushReadMessagesNotice")
	proto.RegisterType((*PutReadMessagesRequest)(nil), "PutReadMessagesRequest")
	proto.RegisterType((*PutReadMessagesResponse)(nil), "PutReadMessagesResponse")
	proto.RegisterType((*PutMessageReadSateNotice)(nil), "PutMessageReadSateNotice")
	proto.RegisterType((*PutChatReadPositionNotice)(nil), "PutChatReadPositionNotice")
	proto.RegisterType((*ReadCountNotification)(nil), "ReadCountNotification")
	proto.RegisterType((*ReadCountNotification_Pair)(nil), "ReadCountNotification.Pair")
	proto.RegisterType((*PushMessageReadCountNotice)(nil), "PushMessageReadCountNotice")
	proto.RegisterType((*PushMessageReadCountNotice_Pair)(nil), "PushMessageReadCountNotice.Pair")
	proto.RegisterType((*PullMessageReadStateRequest)(nil), "PullMessageReadStateRequest")
	proto.RegisterType((*PullMessageReadStateRequest_Pair)(nil), "PullMessageReadStateRequest.Pair")
	proto.RegisterType((*PullMessageReadStateResponse)(nil), "PullMessageReadStateResponse")
	proto.RegisterType((*PullMessageReadStateResponse_ReadState)(nil), "PullMessageReadStateResponse.ReadState")
	proto.RegisterType((*PullMessageIReadStateRequest)(nil), "PullMessageIReadStateRequest")
	proto.RegisterType((*PullMessageIReadStateResponse)(nil), "PullMessageIReadStateResponse")
	proto.RegisterType((*PullMessageMeReadStateRequest)(nil), "PullMessageMeReadStateRequest")
	proto.RegisterType((*PullMessageMeReadStateResponse)(nil), "PullMessageMeReadStateResponse")
	proto.RegisterType((*PushMessagesRequest)(nil), "PushMessagesRequest")
	proto.RegisterType((*PushMessagesResponse)(nil), "PushMessagesResponse")
	proto.RegisterType((*PullMessagesByIdsRequest)(nil), "PullMessagesByIdsRequest")
	proto.RegisterType((*PullMessagesByIdsResponse)(nil), "PullMessagesByIdsResponse")
	proto.RegisterType((*PullMessagesByPositionsRequest)(nil), "PullMessagesByPositionsRequest")
	proto.RegisterType((*PullMessagesByPositionsResponse)(nil), "PullMessagesByPositionsResponse")
	proto.RegisterType((*PutTransmitMessageRequest)(nil), "PutTransmitMessageRequest")
	proto.RegisterType((*PutTransmitMessageResponse)(nil), "PutTransmitMessageResponse")
	proto.RegisterType((*PullUnreadAtMessageIdsRequest)(nil), "PullUnreadAtMessageIdsRequest")
	proto.RegisterType((*PullUnreadAtMessageIdsResponse)(nil), "PullUnreadAtMessageIdsResponse")
	proto.RegisterType((*PutCopyMessagesRequest)(nil), "PutCopyMessagesRequest")
	proto.RegisterType((*PutCopyMessagesResponse)(nil), "PutCopyMessagesResponse")
	proto.RegisterEnum("PullChatMessagesRequest_Type", PullChatMessagesRequest_Type_name, PullChatMessagesRequest_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0x5b, 0x6f, 0xdb, 0xd6,
	0x1d, 0x37, 0x29, 0xc9, 0x12, 0xff, 0xb2, 0x95, 0xf4, 0xc4, 0x49, 0x64, 0xda, 0x8e, 0x15, 0xa2,
	0x49, 0xd5, 0x01, 0x39, 0x6e, 0xb4, 0x61, 0x69, 0xdd, 0x35, 0xab, 0xed, 0xb8, 0x9b, 0xb7, 0x26,
	0x15, 0x18, 0x07, 0x01, 0xf6, 0x22, 0x30, 0xe2, 0xb1, 0x4d, 0x54, 0x22, 0x35, 0x9e, 0xc3, 0x35,
	0xfa, 0x12, 0x03, 0x36, 0xec, 0x65, 0x2f, 0xc3, 0x1e, 0x86, 0x61, 0xd8, 0x4b, 0x31, 0x60, 0xc0,
	0xf6, 0xb0, 0x0f, 0xb0, 0xd7, 0x7d, 0x95, 0x00, 0x7b, 0x1f, 0xce, 0x85, 0x14, 0x29, 0x92, 0x92,
	0x97, 0xd4, 0x6f, 0xe4, 0xff, 0x7e, 0xf9, 0x9d, 0xff, 0xb9, 0x40, 0x6b, 0x4c, 0x28, 0x75, 0xce,
	0x09, 0xc5, 0x93, 0x30, 0x60, 0x81, 0xd9, 0x22, 0x3e, 0xf3, 0x98, 0x17, 0xff, 0x5b, 0xbf, 0xa9,
	0xc2, 0x7b, 0xfd, 0x88, 0x3d, 0x95, 0x52, 0x36, 0xf9, 0x65, 0x44, 0x28, 0x43, 0x77, 0xa1, 0xca,
	0xa6, 0x13, 0xd2, 0xd6, 0x3a, 0x5a, 0xb7, 0xd5, 0x5b, 0xc7, 0x8a, 0x8d, 0x4f, 0xa7, 0x13, 0x62,
	0x0b, 0x16, 0xfa, 0x01, 0xd4, 0x87, 0x81, 0xcf, 0x88, 0xcf, 0xda, 0x7a, 0x47, 0xeb, 0x36, 0x7b,
	0x26, 0xce, 0xd9, 0xc1, 0x47, 0x52, 0xc2, 0x8e, 0x45, 0xd1, 0x6d, 0xa8, 0x0f, 0x2f, 0x1c, 0x36,
	0xf0, 0xdc, 0x76, 0xa5, 0xa3, 0x75, 0x0d, 0x7b, 0x95, 0xff, 0x9e, 0xb8, 0x9c, 0x11, 0x06, 0x81,
	0x60, 0x54, 0x25, 0x83, 0xff, 0x9e, 0xb8, 0x68, 0x0b, 0x8c, 0x89, 0x13, 0x12, 0x5f, 0xb0, 0x6a,
	0x82, 0xd5, 0x90, 0x84, 0x13, 0x17, 0x5d, 0x87, 0xca, 0xd0, 0x73, 0xdb, 0xab, 0x82, 0xcc, 0x3f,
	0xd1, 0x3d, 0x68, 0x7a, 0x74, 0xe0, 0x07, 0xcc, 0x3b, 0xf3, 0x88, 0xdb, 0xae, 0x77, 0xb4, 0x6e,
	0x63, 0xbf, 0xca, 0xc2, 0x88, 0xd8, 0xe0, 0xd1, 0x67, 0x8a, 0x8e, 0xee, 0xc3, 0x1a, 0x25, 0xbe,
	0x3b, 0x60, 0xc1, 0x80, 0x07, 0xd0, 0x6e, 0xa4, 0xe5, 0x38, 0xe7, 0x34, 0x38, 0xba, 0x70, 0x98,
	0xf9, 0x46, 0x83, 0xba, 0x4a, 0x02, 0x21, 0xa8, 0x32, 0xf2, 0x9a, 0x89, 0xa2, 0x18, 0xb6, 0xf8,
	0xe6, 0xd1, 0x79, 0x63, 0xe7, 0x9c, 0x0c, 0xbe, 0x26, 0x53, 0x51, 0x07, 0xc3, 0x6e, 0x08, 0xc2,
	0xcf, 0xc9, 0x14, 0x6d, 0x40, 0x8d, 0x79, 0x6c, 0x44, 0x54, 0xaa, 0xf2, 0x07, 0x75, 0xa0, 0xe9,
	0x30, 0xe6, 0x0c, 0x2f, 0xc6, 0xc4, 0x67, 0xb4, 0x5d, 0xed, 0x54, 0xba, 0x86, 0x9d, 0x26, 0xa1,
	0xdd, 0x6c, 0x0e, 0x3c, 0xe9, 0x46, 0x26, 0xfa, 0x4d, 0x68, 0x9c, 0x79, 0x23, 0xe9, 0x54, 0xe6,
	0x5e, 0xe7, 0xff, 0xdc, 0xe7, 0x16, 0x18, 0x4e, 0xe4, 0x7a, 0x81, 0xe0, 0xd5, 0x65, 0x40, 0x82,
	0xc0, 0x99, 0xf7, 0xa0, 0x25, 0x99, 0x6e, 0x14, 0x3a, 0xcc, 0x0b, 0x7c, 0x91, 0x77, 0xcd, 0x5e,
	0x17, 0xd4, 0x27, 0x8a, 0x68, 0xfd, 0x53, 0x03, 0x94, 0xee, 0x25, 0x9d, 0x04, 0x3e, 0x25, 0xc8,
	0x82, 0xba, 0x02, 0x53, 0x5b, 0xeb, 0xe8, 0xdd, 0x66, 0xaf, 0x11, 0xe3, 0xc2, 0x8e, 0x19, 0xe8,
	0x73, 0x30, 0x26, 0x01, 0xf5, 0xb8, 0x19, 0xda, 0xd6, 0x3b, 0x95, 0x6e, 0xb3, 0x67, 0xe1, 0xbc,
	0x2d, 0xdc, 0x8f, 0x85, 0x8e, 0x7d, 0x16, 0x4e, 0xed, 0x99, 0x92, 0xf9, 0x23, 0x68, 0x65, 0x99,
	0xbc, 0xc9, 0x3c, 0x19, 0x59, 0x76, 0xfe, 0xc9, 0x0b, 0xfb, 0x2b, 0x67, 0x14, 0x11, 0x51, 0xf1,
	0x9a, 0x2d, 0x7f, 0xf6, 0xf5, 0x8f, 0x35, 0xeb, 0xb7, 0x1a, 0xdc, 0xe8, 0x3b, 0x6c, 0x78, 0x31,
	0x07, 0xe8, 0x1f, 0xce, 0xd0, 0x2a, 0x63, 0xdf, 0xc6, 0x05, 0x62, 0x79, 0xbc, 0xb6, 0x40, 0xf7,
	0xdc, 0xb6, 0xde, 0xd1, 0xbb, 0x86, 0xad, 0x7b, 0xae, 0xf9, 0xfd, 0xc5, 0x70, 0x48, 0x3a, 0xae,
	0xa7, 0x3a, 0x6e, 0xed, 0xc3, 0x46, 0xd6, 0xd9, 0xe5, 0x0b, 0x6a, 0xdd, 0x87, 0x8d, 0x27, 0x64,
	0x44, 0x18, 0x99, 0x4b, 0x48, 0x06, 0xa6, 0xc5, 0x81, 0x59, 0x0f, 0xe1, 0xe6, 0x9c, 0x9c, 0x72,
	0xd2, 0xce, 0x3a, 0x31, 0x66, 0xa6, 0xff, 0xa3, 0xc1, 0xed, 0x7e, 0x34, 0x1a, 0x71, 0xa0, 0x2b,
	0x2d, 0x1a, 0x9b, 0x4f, 0xad, 0x53, 0xa9, 0x15, 0xaf, 0xd3, 0x1d, 0x68, 0xc4, 0xbd, 0x92, 0xd5,
	0xdf, 0xd7, 0x3e, 0xb2, 0x13, 0x12, 0x6a, 0x43, 0x6d, 0x18, 0x44, 0x3e, 0x13, 0x90, 0xaf, 0xed,
	0xeb, 0xbd, 0x8f, 0x6c, 0x49, 0x40, 0x9f, 0xa8, 0x91, 0x52, 0xed, 0xe8, 0xdd, 0x56, 0x6f, 0x07,
	0x97, 0x78, 0x16, 0x23, 0x66, 0x7f, 0xf5, 0xcb, 0x83, 0xd3, 0xe3, 0xe7, 0xa7, 0x72, 0xd4, 0x58,
	0x1f, 0x42, 0x95, 0x53, 0x11, 0xc0, 0xea, 0xe1, 0xf1, 0x17, 0x5f, 0xd9, 0xc7, 0xd7, 0x35, 0x64,
	0x40, 0xed, 0xe0, 0x8b, 0xd3, 0x63, 0xfb, 0xba, 0xce, 0xc9, 0x52, 0xfc, 0x7a, 0xc5, 0xfa, 0xb3,
	0x06, 0xed, 0xbc, 0x65, 0x55, 0x8a, 0x23, 0x68, 0xc4, 0xd3, 0xb0, 0xad, 0x09, 0x6c, 0x7e, 0x80,
	0xcb, 0x84, 0xe3, 0x4e, 0x28, 0x80, 0x26, 0x8a, 0xe6, 0x31, 0xac, 0x67, 0x58, 0x05, 0xf0, 0xbc,
	0x93, 0x86, 0x67, 0xba, 0xab, 0x29, 0xa0, 0x3e, 0x85, 0x1b, 0xfd, 0x88, 0xd9, 0xc4, 0x71, 0x0f,
	0xf8, 0xda, 0x2b, 0xac, 0xbb, 0x96, 0xa9, 0x3b, 0xa8, 0x10, 0x06, 0x02, 0x90, 0x9c, 0x67, 0x28,
	0xca, 0x89, 0x6b, 0x3d, 0x83, 0x8d, 0xac, 0x39, 0x95, 0xf2, 0xdb, 0xda, 0x13, 0xe1, 0xd1, 0x8b,
	0xc4, 0x20, 0x1f, 0x3d, 0xc3, 0xb7, 0x37, 0xf7, 0x3b, 0x0d, 0x4c, 0x5e, 0xe9, 0xc4, 0xde, 0x73,
	0xe6, 0xb0, 0x88, 0xce, 0x56, 0x67, 0x6d, 0xe2, 0x78, 0x61, 0xdc, 0x95, 0x0e, 0x2e, 0x97, 0xc5,
	0x7d, 0xc7, 0x0b, 0x6d, 0x29, 0x6e, 0x3e, 0x86, 0x2a, 0xff, 0x7d, 0xeb, 0xb0, 0xbe, 0xd5, 0x60,
	0xab, 0xd0, 0x95, 0xaa, 0xde, 0xa3, 0x6c, 0x5c, 0x77, 0xf1, 0x02, 0xe1, 0x4c, 0x60, 0x2f, 0xdf,
	0x2d, 0x30, 0xae, 0xe7, 0xd1, 0x41, 0x48, 0x1c, 0xb9, 0x4d, 0x36, 0xec, 0x55, 0x8f, 0x72, 0xbf,
	0x56, 0x08, 0xb7, 0xe2, 0xbe, 0xc4, 0x28, 0x5c, 0xd6, 0x9a, 0x5d, 0x68, 0xce, 0x5c, 0xc9, 0xa1,
	0x6c, 0xd8, 0x90, 0xf8, 0xa2, 0xe8, 0x4e, 0x6a, 0x49, 0xab, 0x65, 0xfb, 0xe0, 0xe1, 0x6c, 0x4d,
	0x5b, 0x53, 0xee, 0x93, 0xa5, 0x5d, 0x2e, 0x9d, 0x12, 0x4b, 0x7d, 0xde, 0x83, 0xb5, 0xb1, 0xf3,
	0x7a, 0x90, 0xf2, 0xab, 0x2b, 0xbf, 0xcd, 0xb1, 0xf3, 0xba, 0x3f, 0x73, 0x7d, 0x3b, 0xe7, 0x5a,
	0xf5, 0xa6, 0x07, 0x37, 0x47, 0x0e, 0x65, 0x83, 0xd8, 0x4f, 0x62, 0x4a, 0x13, 0x7b, 0xc2, 0x0d,
	0xce, 0x54, 0x4a, 0xb1, 0x39, 0xf4, 0x3d, 0x78, 0xcf, 0x27, 0xdf, 0x24, 0x2a, 0x72, 0x52, 0xc9,
	0x3d, 0xe4, 0x9a, 0x4f, 0xbe, 0x51, 0xe2, 0x47, 0x9c, 0x6c, 0x9d, 0xf2, 0x41, 0x32, 0xdb, 0xb7,
	0x1c, 0xf7, 0xb9, 0xc3, 0xc8, 0xbb, 0xd6, 0xda, 0xea, 0xc3, 0x66, 0x3f, 0x62, 0x7c, 0xe0, 0x70,
	0x93, 0x71, 0x60, 0xcb, 0xcc, 0x9a, 0xf3, 0x43, 0x37, 0xd5, 0x9d, 0x3f, 0x6a, 0x70, 0x93, 0xdb,
	0x12, 0x51, 0xcb, 0x13, 0xc2, 0x50, 0x6c, 0xe3, 0xe8, 0x61, 0x16, 0xbd, 0x5b, 0xb8, 0x50, 0x2c,
	0x83, 0xdb, 0xd3, 0x77, 0xc4, 0xed, 0x46, 0x66, 0xfc, 0xab, 0xd1, 0x6f, 0xfd, 0x5a, 0xe7, 0xab,
	0x9f, 0x5e, 0xa4, 0x8a, 0x99, 0x84, 0x31, 0x24, 0x45, 0xab, 0xbf, 0x4c, 0x36, 0x13, 0xec, 0x3f,
	0xb4, 0xab, 0x88, 0x96, 0xf7, 0x90, 0xab, 0x33, 0x12, 0x8a, 0x1e, 0xca, 0xf3, 0x19, 0x28, 0x12,
	0xc7, 0xee, 0x5d, 0x58, 0x8b, 0x7c, 0xbe, 0x36, 0x15, 0x80, 0x6a, 0x42, 0xbb, 0x29, 0x69, 0x22,
	0x58, 0xee, 0x38, 0x25, 0xb0, 0x2a, 0x04, 0x8c, 0x84, 0x6d, 0xfd, 0x4b, 0xcd, 0x9d, 0x34, 0xba,
	0x98, 0xc3, 0x92, 0xcd, 0xbd, 0x70, 0xee, 0x94, 0x08, 0xa7, 0x4b, 0x82, 0xde, 0x07, 0xf0, 0x09,
	0x71, 0x07, 0x11, 0x25, 0x21, 0x15, 0x09, 0x37, 0xf6, 0x6b, 0x67, 0xce, 0x88, 0x12, 0xdb, 0xe0,
	0x8c, 0x17, 0x9c, 0xfe, 0xce, 0x63, 0xf3, 0x8d, 0x0e, 0xdb, 0xc5, 0x11, 0xa9, 0xb5, 0xf9, 0x0c,
	0x9a, 0x22, 0x7d, 0xca, 0xa9, 0x71, 0x16, 0x0f, 0xf0, 0x22, 0x1d, 0x9c, 0x50, 0xd4, 0x8e, 0x2b,
	0x0a, 0x28, 0x09, 0xe6, 0xef, 0x35, 0x30, 0x12, 0x3e, 0xb2, 0x60, 0x5d, 0x58, 0xe7, 0x49, 0x8a,
	0x16, 0x69, 0xf2, 0x08, 0xcd, 0x89, 0x3c, 0x41, 0xde, 0xa3, 0xfb, 0x70, 0x4d, 0xf5, 0x28, 0x91,
	0x92, 0x8b, 0x71, 0x5d, 0x92, 0x63, 0xb9, 0xf9, 0x5e, 0x56, 0x96, 0xf5, 0xb2, 0x3a, 0xd7, 0x4b,
	0xf3, 0x0c, 0xae, 0xcd, 0x85, 0x5e, 0x70, 0x22, 0xf8, 0x2c, 0x7b, 0x22, 0xf8, 0xe0, 0x92, 0xa5,
	0x48, 0x1f, 0x18, 0x7e, 0x9c, 0xa9, 0xf9, 0x49, 0x0e, 0x33, 0x73, 0xa3, 0x47, 0xcb, 0x8d, 0x9e,
	0x6f, 0x35, 0xd8, 0x29, 0xb1, 0xa0, 0xda, 0xf6, 0x55, 0xaa, 0x6d, 0x51, 0xdc, 0x36, 0x8c, 0x17,
	0x2a, 0x25, 0xc1, 0x46, 0xf3, 0x7d, 0x8b, 0xa8, 0xf9, 0xd9, 0xac, 0x36, 0xd1, 0xe5, 0x0e, 0xf3,
	0x8d, 0x74, 0xca, 0x9f, 0x67, 0x02, 0x7e, 0x4a, 0xfe, 0xff, 0x9c, 0xff, 0xa6, 0xc1, 0x9d, 0x32,
	0x13, 0x2a, 0xe9, 0x7e, 0x51, 0xd2, 0x7b, 0x78, 0xb1, 0xd6, 0x55, 0x66, 0xfd, 0x07, 0x5d, 0x9e,
	0xbd, 0xe6, 0x37, 0xdb, 0xc7, 0xb9, 0xd3, 0xab, 0x85, 0x0b, 0xe4, 0xca, 0x0e, 0xae, 0xe8, 0x53,
	0xa8, 0xfb, 0x62, 0x88, 0xc6, 0x17, 0xb3, 0xbb, 0x85, 0xea, 0x72, 0xd0, 0x2a, 0xed, 0x58, 0xe3,
	0x3b, 0x3a, 0xf5, 0x9a, 0x47, 0xb0, 0x96, 0xb6, 0x5f, 0x60, 0x65, 0x27, 0x6b, 0xa5, 0xae, 0xe2,
	0x49, 0x17, 0xe8, 0x11, 0x3f, 0xeb, 0xa6, 0x03, 0x57, 0x9d, 0x5c, 0x8a, 0x86, 0x4f, 0xe5, 0xdd,
	0x20, 0x56, 0x3c, 0x9c, 0x9e, 0xb8, 0xf4, 0xd2, 0x50, 0xfa, 0x8b, 0xc6, 0xb7, 0xee, 0x9c, 0xb6,
	0xf2, 0xfd, 0x24, 0xd7, 0x9c, 0x2e, 0x2e, 0x95, 0xbe, 0xea, 0xbb, 0xc5, 0xcb, 0x0c, 0xe8, 0xe9,
	0xe1, 0x34, 0xb9, 0x50, 0x2f, 0x3d, 0xb8, 0x6d, 0xcf, 0xdf, 0xdf, 0x6b, 0xa9, 0xbb, 0xb9, 0xf5,
	0x77, 0x0d, 0x76, 0x4b, 0x2d, 0xab, 0x4a, 0xfc, 0x2c, 0x57, 0x09, 0x8c, 0x97, 0xe8, 0xbc, 0x55,
	0x3d, 0x6a, 0x97, 0xaf, 0xc7, 0xbf, 0x45, 0xeb, 0xd8, 0x69, 0xe8, 0xf8, 0x74, 0xec, 0xcd, 0xbf,
	0x75, 0x6d, 0x42, 0x43, 0xd5, 0x22, 0x6e, 0x7b, 0x5d, 0x16, 0x83, 0xe6, 0xf6, 0x41, 0x3d, 0x7b,
	0x7e, 0xf8, 0x18, 0xaa, 0x43, 0xae, 0x55, 0x11, 0x69, 0xbe, 0x8f, 0x4b, 0x7d, 0xe0, 0x23, 0xcf,
	0x55, 0xc9, 0x09, 0x0d, 0xf3, 0x11, 0x18, 0x09, 0x69, 0xd9, 0x70, 0x30, 0xd2, 0xa9, 0xfc, 0x55,
	0x5c, 0xa4, 0xf2, 0x6e, 0x54, 0xf1, 0x8f, 0x73, 0xc5, 0xff, 0x10, 0x97, 0x8b, 0x5f, 0x35, 0x0e,
	0x77, 0xe5, 0xfc, 0x7e, 0x21, 0x36, 0xd3, 0x83, 0xd8, 0xfb, 0x6c, 0xd1, 0x59, 0x07, 0x12, 0xa8,
	0x45, 0x02, 0x97, 0x5d, 0xd3, 0x2f, 0xc5, 0xe5, 0xe4, 0x28, 0x98, 0x4c, 0xe7, 0xe7, 0xe5, 0x32,
	0x55, 0xb4, 0x0d, 0xa0, 0x9e, 0xff, 0x66, 0xdd, 0x6d, 0x30, 0xf1, 0xee, 0x77, 0xe2, 0x5a, 0x7f,
	0x12, 0xaf, 0x23, 0x73, 0x96, 0x55, 0x54, 0x87, 0xb9, 0x32, 0xdf, 0xc7, 0x25, 0xb2, 0x57, 0x5c,
	0xe3, 0xde, 0x7f, 0x2b, 0xd0, 0x52, 0xe4, 0x9f, 0x84, 0x84, 0x30, 0x12, 0xa2, 0x87, 0x50, 0xa5,
	0xc4, 0x77, 0x11, 0xca, 0x3f, 0xc8, 0x9a, 0x37, 0x0a, 0x1e, 0xe3, 0xac, 0x15, 0x8e, 0x1b, 0xa6,
	0x30, 0x82, 0xcc, 0x72, 0x1c, 0x9b, 0x5b, 0x0b, 0xd0, 0x64, 0xad, 0xa0, 0xc7, 0x50, 0x39, 0x27,
	0x0c, 0x6d, 0xe2, 0xb2, 0x31, 0x6b, 0x9a, 0xe5, 0x53, 0xd1, 0x5a, 0x41, 0x2f, 0xa0, 0x75, 0x4e,
	0x58, 0x6a, 0x42, 0xa0, 0x5d, 0xbc, 0x78, 0x92, 0x99, 0x9d, 0x65, 0xc3, 0xc5, 0x5a, 0x41, 0x9f,
	0xc0, 0xaa, 0x2b, 0xde, 0xc6, 0xd0, 0x4d, 0x5c, 0xf4, 0x98, 0x66, 0xde, 0xc2, 0x85, 0x6f, 0x67,
	0xd6, 0x0a, 0x7a, 0x0a, 0x6b, 0xe7, 0x84, 0xcd, 0xce, 0x9e, 0xdb, 0x8b, 0x8e, 0xe2, 0xe6, 0xce,
	0xc2, 0x73, 0x9d, 0xb5, 0x82, 0x7e, 0x0a, 0xd7, 0xce, 0x09, 0x4b, 0xbf, 0x37, 0xa1, 0x76, 0xd9,
	0x4b, 0x98, 0xb9, 0x59, 0xfa, 0x38, 0x65, 0xad, 0x1c, 0x7e, 0x09, 0xb7, 0x86, 0xc1, 0x18, 0x53,
	0x8a, 0x1d, 0xdf, 0x0d, 0x03, 0xcf, 0xc5, 0x23, 0x27, 0xfc, 0x1a, 0x4f, 0x5e, 0xfd, 0xa2, 0x77,
	0xee, 0x31, 0xfc, 0x6a, 0xca, 0x88, 0x8b, 0x83, 0xf0, 0x7c, 0x8f, 0x90, 0x3d, 0xce, 0xd9, 0xf3,
	0xc6, 0x0f, 0xc4, 0x8b, 0xff, 0xab, 0xe8, 0x6c, 0xcf, 0x1b, 0x8b, 0xcf, 0xbd, 0x18, 0x8c, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x1b, 0xad, 0x77, 0x26, 0x18, 0x00, 0x00,
}
