# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comment.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rcomment.proto\")\n\x13PullCommentsReqeust\x12\x12\n\nmessage_id\x18\x01 \x02(\t\":\n\x14PullCommentsResponse\x12\x0f\n\x07root_id\x18\x01 \x02(\t\x12\x11\n\tchild_ids\x18\x02 \x03(\t2N\n\x0e\x43ommentGreeter\x12<\n\x0bgetComments\x12\x14.PullCommentsReqeust\x1a\x15.PullCommentsResponse\"\x00\x42I\n\x16\x63om.ss.android.lark.pbZ/git.byted.org/ee/lark/im-protobuf/improto/posts')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PULLCOMMENTSREQEUST = _descriptor.Descriptor(
  name='PullCommentsReqeust',
  full_name='PullCommentsReqeust',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='PullCommentsReqeust.message_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=58,
)


_PULLCOMMENTSRESPONSE = _descriptor.Descriptor(
  name='PullCommentsResponse',
  full_name='PullCommentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_id', full_name='PullCommentsResponse.root_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_ids', full_name='PullCommentsResponse.child_ids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['PullCommentsReqeust'] = _PULLCOMMENTSREQEUST
DESCRIPTOR.message_types_by_name['PullCommentsResponse'] = _PULLCOMMENTSRESPONSE

PullCommentsReqeust = _reflection.GeneratedProtocolMessageType('PullCommentsReqeust', (_message.Message,), dict(
  DESCRIPTOR = _PULLCOMMENTSREQEUST,
  __module__ = 'comment_pb2'
  # @@protoc_insertion_point(class_scope:PullCommentsReqeust)
  ))
_sym_db.RegisterMessage(PullCommentsReqeust)

PullCommentsResponse = _reflection.GeneratedProtocolMessageType('PullCommentsResponse', (_message.Message,), dict(
  DESCRIPTOR = _PULLCOMMENTSRESPONSE,
  __module__ = 'comment_pb2'
  # @@protoc_insertion_point(class_scope:PullCommentsResponse)
  ))
_sym_db.RegisterMessage(PullCommentsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.ss.android.lark.pbZ/git.byted.org/ee/lark/im-protobuf/improto/posts'))
# @@protoc_insertion_point(module_scope)
