# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import entities_pb2 as entities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='groups.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cgroups.proto\x1a\x0e\x65ntities.proto\"Z\n\x1aPutEasemobGroupChatRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\x12\x14\n\ngroup_name\x18\x02 \x01(\t:\x00\x12\x14\n\ngroup_desc\x18\x03 \x01(\t:\x00\"N\n\x1bPutEasemobGroupChatResponse\x12\x15\n\rgroup_chat_id\x18\x01 \x02(\t\x12\x18\n\x10\x65\x61semob_group_id\x18\x02 \x02(\t2U\n\x0cGroupGreeter\x12\x45\n\x06\x63reate\x12\x1b.PutEasemobGroupChatRequest\x1a\x1c.PutEasemobGroupChatResponse\"\x00\x42\x18\n\x16\x63om.ss.android.lark.pb')
  ,
  dependencies=[entities__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PUTEASEMOBGROUPCHATREQUEST = _descriptor.Descriptor(
  name='PutEasemobGroupChatRequest',
  full_name='PutEasemobGroupChatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_ids', full_name='PutEasemobGroupChatRequest.user_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='PutEasemobGroupChatRequest.group_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_desc', full_name='PutEasemobGroupChatRequest.group_desc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=122,
)


_PUTEASEMOBGROUPCHATRESPONSE = _descriptor.Descriptor(
  name='PutEasemobGroupChatResponse',
  full_name='PutEasemobGroupChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_chat_id', full_name='PutEasemobGroupChatResponse.group_chat_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='easemob_group_id', full_name='PutEasemobGroupChatResponse.easemob_group_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['PutEasemobGroupChatRequest'] = _PUTEASEMOBGROUPCHATREQUEST
DESCRIPTOR.message_types_by_name['PutEasemobGroupChatResponse'] = _PUTEASEMOBGROUPCHATRESPONSE

PutEasemobGroupChatRequest = _reflection.GeneratedProtocolMessageType('PutEasemobGroupChatRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTEASEMOBGROUPCHATREQUEST,
  __module__ = 'groups_pb2'
  # @@protoc_insertion_point(class_scope:PutEasemobGroupChatRequest)
  ))
_sym_db.RegisterMessage(PutEasemobGroupChatRequest)

PutEasemobGroupChatResponse = _reflection.GeneratedProtocolMessageType('PutEasemobGroupChatResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTEASEMOBGROUPCHATRESPONSE,
  __module__ = 'groups_pb2'
  # @@protoc_insertion_point(class_scope:PutEasemobGroupChatResponse)
  ))
_sym_db.RegisterMessage(PutEasemobGroupChatResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.ss.android.lark.pb'))
# @@protoc_insertion_point(module_scope)
