# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: images.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import entities_pb2 as entities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='images.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cimages.proto\x1a\x0e\x65ntities.proto\"\"\n\x12UploadImageRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\"J\n\x13UploadImageResponse\x12\x15\n\x05image\x18\x01 \x02(\x0b\x32\x06.Image\x12\x1c\n\timage_set\x18\x02 \x01(\x0b\x32\t.ImageSet2C\n\x0cImageGreeter\x12\x33\n\x04send\x12\x13.UploadImageRequest\x1a\x14.UploadImageResponse\"\x00\x42J\n\x16\x63om.ss.android.lark.pbZ0git.byted.org/ee/lark/im-protobuf/improto/images')
  ,
  dependencies=[entities__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UPLOADIMAGEREQUEST = _descriptor.Descriptor(
  name='UploadImageRequest',
  full_name='UploadImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='UploadImageRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=66,
)


_UPLOADIMAGERESPONSE = _descriptor.Descriptor(
  name='UploadImageResponse',
  full_name='UploadImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='UploadImageResponse.image', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_set', full_name='UploadImageResponse.image_set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=142,
)

_UPLOADIMAGERESPONSE.fields_by_name['image'].message_type = entities__pb2._IMAGE
_UPLOADIMAGERESPONSE.fields_by_name['image_set'].message_type = entities__pb2._IMAGESET
DESCRIPTOR.message_types_by_name['UploadImageRequest'] = _UPLOADIMAGEREQUEST
DESCRIPTOR.message_types_by_name['UploadImageResponse'] = _UPLOADIMAGERESPONSE

UploadImageRequest = _reflection.GeneratedProtocolMessageType('UploadImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADIMAGEREQUEST,
  __module__ = 'images_pb2'
  # @@protoc_insertion_point(class_scope:UploadImageRequest)
  ))
_sym_db.RegisterMessage(UploadImageRequest)

UploadImageResponse = _reflection.GeneratedProtocolMessageType('UploadImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADIMAGERESPONSE,
  __module__ = 'images_pb2'
  # @@protoc_insertion_point(class_scope:UploadImageResponse)
  ))
_sym_db.RegisterMessage(UploadImageResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.ss.android.lark.pbZ0git.byted.org/ee/lark/im-protobuf/improto/images'))
# @@protoc_insertion_point(module_scope)
