# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pack.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import entities_pb2 as entities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pack.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\npack.proto\x1a\x0e\x65ntities.proto\"\xc0\x02\n\x0cPackResponse\x12-\n\x08messages\x18\x01 \x03(\x0b\x32\x1b.PackResponse.MessagesEntry\x12\'\n\x05\x63hats\x18\x02 \x03(\x0b\x32\x18.PackResponse.ChatsEntry\x12-\n\x08\x63hatters\x18\x03 \x03(\x0b\x32\x1b.PackResponse.ChattersEntry\x1a\x39\n\rMessagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Message:\x02\x38\x01\x1a\x33\n\nChatsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Chat:\x02\x38\x01\x1a\x39\n\rChattersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Chatter:\x02\x38\x01\x42H\n\x16\x63om.ss.android.lark.pbZ.git.byted.org/ee/lark/im-protobuf/improto/pack')
  ,
  dependencies=[entities__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PACKRESPONSE_MESSAGESENTRY = _descriptor.Descriptor(
  name='MessagesEntry',
  full_name='PackResponse.MessagesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PackResponse.MessagesEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PackResponse.MessagesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=239,
)

_PACKRESPONSE_CHATSENTRY = _descriptor.Descriptor(
  name='ChatsEntry',
  full_name='PackResponse.ChatsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PackResponse.ChatsEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PackResponse.ChatsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=292,
)

_PACKRESPONSE_CHATTERSENTRY = _descriptor.Descriptor(
  name='ChattersEntry',
  full_name='PackResponse.ChattersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PackResponse.ChattersEntry.key', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PackResponse.ChattersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=351,
)

_PACKRESPONSE = _descriptor.Descriptor(
  name='PackResponse',
  full_name='PackResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='PackResponse.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chats', full_name='PackResponse.chats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chatters', full_name='PackResponse.chatters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PACKRESPONSE_MESSAGESENTRY, _PACKRESPONSE_CHATSENTRY, _PACKRESPONSE_CHATTERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=351,
)

_PACKRESPONSE_MESSAGESENTRY.fields_by_name['value'].message_type = entities__pb2._MESSAGE
_PACKRESPONSE_MESSAGESENTRY.containing_type = _PACKRESPONSE
_PACKRESPONSE_CHATSENTRY.fields_by_name['value'].message_type = entities__pb2._CHAT
_PACKRESPONSE_CHATSENTRY.containing_type = _PACKRESPONSE
_PACKRESPONSE_CHATTERSENTRY.fields_by_name['value'].message_type = entities__pb2._CHATTER
_PACKRESPONSE_CHATTERSENTRY.containing_type = _PACKRESPONSE
_PACKRESPONSE.fields_by_name['messages'].message_type = _PACKRESPONSE_MESSAGESENTRY
_PACKRESPONSE.fields_by_name['chats'].message_type = _PACKRESPONSE_CHATSENTRY
_PACKRESPONSE.fields_by_name['chatters'].message_type = _PACKRESPONSE_CHATTERSENTRY
DESCRIPTOR.message_types_by_name['PackResponse'] = _PACKRESPONSE

PackResponse = _reflection.GeneratedProtocolMessageType('PackResponse', (_message.Message,), dict(

  MessagesEntry = _reflection.GeneratedProtocolMessageType('MessagesEntry', (_message.Message,), dict(
    DESCRIPTOR = _PACKRESPONSE_MESSAGESENTRY,
    __module__ = 'pack_pb2'
    # @@protoc_insertion_point(class_scope:PackResponse.MessagesEntry)
    ))
  ,

  ChatsEntry = _reflection.GeneratedProtocolMessageType('ChatsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PACKRESPONSE_CHATSENTRY,
    __module__ = 'pack_pb2'
    # @@protoc_insertion_point(class_scope:PackResponse.ChatsEntry)
    ))
  ,

  ChattersEntry = _reflection.GeneratedProtocolMessageType('ChattersEntry', (_message.Message,), dict(
    DESCRIPTOR = _PACKRESPONSE_CHATTERSENTRY,
    __module__ = 'pack_pb2'
    # @@protoc_insertion_point(class_scope:PackResponse.ChattersEntry)
    ))
  ,
  DESCRIPTOR = _PACKRESPONSE,
  __module__ = 'pack_pb2'
  # @@protoc_insertion_point(class_scope:PackResponse)
  ))
_sym_db.RegisterMessage(PackResponse)
_sym_db.RegisterMessage(PackResponse.MessagesEntry)
_sym_db.RegisterMessage(PackResponse.ChatsEntry)
_sym_db.RegisterMessage(PackResponse.ChattersEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.ss.android.lark.pbZ.git.byted.org/ee/lark/im-protobuf/improto/pack'))
_PACKRESPONSE_MESSAGESENTRY.has_options = True
_PACKRESPONSE_MESSAGESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PACKRESPONSE_CHATSENTRY.has_options = True
_PACKRESPONSE_CHATSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PACKRESPONSE_CHATTERSENTRY.has_options = True
_PACKRESPONSE_CHATTERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
