# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thread.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import entities_pb2 as entities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='thread.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cthread.proto\x1a\x0e\x65ntities.proto\"&\n\x11PullThreadRequest\x12\x11\n\tthread_id\x18\x01 \x02(\t\"\xbf\x01\n\x12PullThreadResponse\x12\x11\n\tthread_id\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x02(\t\x12\x11\n\treply_ids\x18\x04 \x03(\t\x12*\n\x06status\x18\x05 \x02(\x0e\x32\x1a.PullThreadResponse.Status\x12\x13\n\x0breply_count\x18\x06 \x02(\x05\"\"\n\x06Status\x12\n\n\x06NORMAL\x10\x00\x12\x0c\n\x08\x41RCHIVED\x10\x01\"E\n\x1bPushThreadReplyCountRequest\x12\x11\n\tthread_id\x18\x01 \x02(\t\x12\x13\n\x0breply_count\x18\x02 \x02(\x05\"\x1e\n\x1cPushThreadReplyCountResponse\"\xb4\x01\n\x18PullThreadRepliesRequest\x12\x11\n\tthread_id\x18\x01 \x02(\t\x12\x11\n\tanchor_id\x18\x02 \x01(\t\x12\x11\n\x05\x63ount\x18\x03 \x01(\x05:\x02\x32\x30\x12\x34\n\x04type\x18\x04 \x02(\x0e\x32\x1e.PullThreadRepliesRequest.Type:\x06LATEST\")\n\x04Type\x12\n\n\x06\x42\x45\x46ORE\x10\x01\x12\t\n\x05\x41\x46TER\x10\x02\x12\n\n\x06LATEST\x10\x03\"\xbe\x01\n\x19PullThreadRepliesResponse\x12\x11\n\tthread_id\x18\x01 \x02(\t\x12:\n\x08messages\x18\x02 \x03(\x0b\x32(.PullThreadRepliesResponse.MessagesEntry\x12\x17\n\x08has_more\x18\x03 \x01(\x08:\x05\x66\x61lse\x1a\x39\n\rMessagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Message:\x02\x38\x01\"O\n\x1aPullThreadReactionsRequest\x12\x12\n\nthread_ids\x18\x01 \x03(\t\x12\x1d\n\x0e\x66\x65tch_chatters\x18\x02 \x01(\x08:\x05\x66\x61lse\"\xb4\x01\n\x1bPullThreadReactionsResponse\x12K\n\x10thread_reactions\x18\x01 \x03(\x0b\x32\x31.PullThreadReactionsResponse.ThreadReactionsEntry\x1aH\n\x14ThreadReactionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.MessageReaction:\x02\x38\x01\"=\n\x19PatchThreadSettingRequest\x12\x11\n\tthread_id\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x01(\t\"\x1c\n\x1aPatchThreadSettingResponseBL\n\x16\x63om.ss.android.lark.pbZ2git.byted.org/ee/lark/im-protobuf/improto/messages')
  ,
  dependencies=[entities__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PULLTHREADRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='PullThreadResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARCHIVED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=230,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_PULLTHREADRESPONSE_STATUS)

_PULLTHREADREPLIESREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='PullThreadRepliesRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEFORE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AFTER', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LATEST', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=509,
  serialized_end=550,
)
_sym_db.RegisterEnumDescriptor(_PULLTHREADREPLIESREQUEST_TYPE)


_PULLTHREADREQUEST = _descriptor.Descriptor(
  name='PullThreadRequest',
  full_name='PullThreadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='PullThreadRequest.thread_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=70,
)


_PULLTHREADRESPONSE = _descriptor.Descriptor(
  name='PullThreadResponse',
  full_name='PullThreadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='PullThreadResponse.thread_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='PullThreadResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_id', full_name='PullThreadResponse.chat_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reply_ids', full_name='PullThreadResponse.reply_ids', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='PullThreadResponse.status', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reply_count', full_name='PullThreadResponse.reply_count', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PULLTHREADRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=264,
)


_PUSHTHREADREPLYCOUNTREQUEST = _descriptor.Descriptor(
  name='PushThreadReplyCountRequest',
  full_name='PushThreadReplyCountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='PushThreadReplyCountRequest.thread_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reply_count', full_name='PushThreadReplyCountRequest.reply_count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=335,
)


_PUSHTHREADREPLYCOUNTRESPONSE = _descriptor.Descriptor(
  name='PushThreadReplyCountResponse',
  full_name='PushThreadReplyCountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=367,
)


_PULLTHREADREPLIESREQUEST = _descriptor.Descriptor(
  name='PullThreadRepliesRequest',
  full_name='PullThreadRepliesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='PullThreadRepliesRequest.thread_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anchor_id', full_name='PullThreadRepliesRequest.anchor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='PullThreadRepliesRequest.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='PullThreadRepliesRequest.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PULLTHREADREPLIESREQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=550,
)


_PULLTHREADREPLIESRESPONSE_MESSAGESENTRY = _descriptor.Descriptor(
  name='MessagesEntry',
  full_name='PullThreadRepliesResponse.MessagesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PullThreadRepliesResponse.MessagesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PullThreadRepliesResponse.MessagesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=743,
)

_PULLTHREADREPLIESRESPONSE = _descriptor.Descriptor(
  name='PullThreadRepliesResponse',
  full_name='PullThreadRepliesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='PullThreadRepliesResponse.thread_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messages', full_name='PullThreadRepliesResponse.messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_more', full_name='PullThreadRepliesResponse.has_more', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PULLTHREADREPLIESRESPONSE_MESSAGESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=743,
)


_PULLTHREADREACTIONSREQUEST = _descriptor.Descriptor(
  name='PullThreadReactionsRequest',
  full_name='PullThreadReactionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_ids', full_name='PullThreadReactionsRequest.thread_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fetch_chatters', full_name='PullThreadReactionsRequest.fetch_chatters', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=824,
)


_PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY = _descriptor.Descriptor(
  name='ThreadReactionsEntry',
  full_name='PullThreadReactionsResponse.ThreadReactionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='PullThreadReactionsResponse.ThreadReactionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='PullThreadReactionsResponse.ThreadReactionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=935,
  serialized_end=1007,
)

_PULLTHREADREACTIONSRESPONSE = _descriptor.Descriptor(
  name='PullThreadReactionsResponse',
  full_name='PullThreadReactionsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_reactions', full_name='PullThreadReactionsResponse.thread_reactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=827,
  serialized_end=1007,
)


_PATCHTHREADSETTINGREQUEST = _descriptor.Descriptor(
  name='PatchThreadSettingRequest',
  full_name='PatchThreadSettingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='PatchThreadSettingRequest.thread_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='PatchThreadSettingRequest.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1009,
  serialized_end=1070,
)


_PATCHTHREADSETTINGRESPONSE = _descriptor.Descriptor(
  name='PatchThreadSettingResponse',
  full_name='PatchThreadSettingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1072,
  serialized_end=1100,
)

_PULLTHREADRESPONSE.fields_by_name['status'].enum_type = _PULLTHREADRESPONSE_STATUS
_PULLTHREADRESPONSE_STATUS.containing_type = _PULLTHREADRESPONSE
_PULLTHREADREPLIESREQUEST.fields_by_name['type'].enum_type = _PULLTHREADREPLIESREQUEST_TYPE
_PULLTHREADREPLIESREQUEST_TYPE.containing_type = _PULLTHREADREPLIESREQUEST
_PULLTHREADREPLIESRESPONSE_MESSAGESENTRY.fields_by_name['value'].message_type = entities__pb2._MESSAGE
_PULLTHREADREPLIESRESPONSE_MESSAGESENTRY.containing_type = _PULLTHREADREPLIESRESPONSE
_PULLTHREADREPLIESRESPONSE.fields_by_name['messages'].message_type = _PULLTHREADREPLIESRESPONSE_MESSAGESENTRY
_PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY.fields_by_name['value'].message_type = entities__pb2._MESSAGEREACTION
_PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY.containing_type = _PULLTHREADREACTIONSRESPONSE
_PULLTHREADREACTIONSRESPONSE.fields_by_name['thread_reactions'].message_type = _PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY
DESCRIPTOR.message_types_by_name['PullThreadRequest'] = _PULLTHREADREQUEST
DESCRIPTOR.message_types_by_name['PullThreadResponse'] = _PULLTHREADRESPONSE
DESCRIPTOR.message_types_by_name['PushThreadReplyCountRequest'] = _PUSHTHREADREPLYCOUNTREQUEST
DESCRIPTOR.message_types_by_name['PushThreadReplyCountResponse'] = _PUSHTHREADREPLYCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['PullThreadRepliesRequest'] = _PULLTHREADREPLIESREQUEST
DESCRIPTOR.message_types_by_name['PullThreadRepliesResponse'] = _PULLTHREADREPLIESRESPONSE
DESCRIPTOR.message_types_by_name['PullThreadReactionsRequest'] = _PULLTHREADREACTIONSREQUEST
DESCRIPTOR.message_types_by_name['PullThreadReactionsResponse'] = _PULLTHREADREACTIONSRESPONSE
DESCRIPTOR.message_types_by_name['PatchThreadSettingRequest'] = _PATCHTHREADSETTINGREQUEST
DESCRIPTOR.message_types_by_name['PatchThreadSettingResponse'] = _PATCHTHREADSETTINGRESPONSE

PullThreadRequest = _reflection.GeneratedProtocolMessageType('PullThreadRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLTHREADREQUEST,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PullThreadRequest)
  ))
_sym_db.RegisterMessage(PullThreadRequest)

PullThreadResponse = _reflection.GeneratedProtocolMessageType('PullThreadResponse', (_message.Message,), dict(
  DESCRIPTOR = _PULLTHREADRESPONSE,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PullThreadResponse)
  ))
_sym_db.RegisterMessage(PullThreadResponse)

PushThreadReplyCountRequest = _reflection.GeneratedProtocolMessageType('PushThreadReplyCountRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUSHTHREADREPLYCOUNTREQUEST,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PushThreadReplyCountRequest)
  ))
_sym_db.RegisterMessage(PushThreadReplyCountRequest)

PushThreadReplyCountResponse = _reflection.GeneratedProtocolMessageType('PushThreadReplyCountResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUSHTHREADREPLYCOUNTRESPONSE,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PushThreadReplyCountResponse)
  ))
_sym_db.RegisterMessage(PushThreadReplyCountResponse)

PullThreadRepliesRequest = _reflection.GeneratedProtocolMessageType('PullThreadRepliesRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLTHREADREPLIESREQUEST,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PullThreadRepliesRequest)
  ))
_sym_db.RegisterMessage(PullThreadRepliesRequest)

PullThreadRepliesResponse = _reflection.GeneratedProtocolMessageType('PullThreadRepliesResponse', (_message.Message,), dict(

  MessagesEntry = _reflection.GeneratedProtocolMessageType('MessagesEntry', (_message.Message,), dict(
    DESCRIPTOR = _PULLTHREADREPLIESRESPONSE_MESSAGESENTRY,
    __module__ = 'thread_pb2'
    # @@protoc_insertion_point(class_scope:PullThreadRepliesResponse.MessagesEntry)
    ))
  ,
  DESCRIPTOR = _PULLTHREADREPLIESRESPONSE,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PullThreadRepliesResponse)
  ))
_sym_db.RegisterMessage(PullThreadRepliesResponse)
_sym_db.RegisterMessage(PullThreadRepliesResponse.MessagesEntry)

PullThreadReactionsRequest = _reflection.GeneratedProtocolMessageType('PullThreadReactionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLTHREADREACTIONSREQUEST,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PullThreadReactionsRequest)
  ))
_sym_db.RegisterMessage(PullThreadReactionsRequest)

PullThreadReactionsResponse = _reflection.GeneratedProtocolMessageType('PullThreadReactionsResponse', (_message.Message,), dict(

  ThreadReactionsEntry = _reflection.GeneratedProtocolMessageType('ThreadReactionsEntry', (_message.Message,), dict(
    DESCRIPTOR = _PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY,
    __module__ = 'thread_pb2'
    # @@protoc_insertion_point(class_scope:PullThreadReactionsResponse.ThreadReactionsEntry)
    ))
  ,
  DESCRIPTOR = _PULLTHREADREACTIONSRESPONSE,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PullThreadReactionsResponse)
  ))
_sym_db.RegisterMessage(PullThreadReactionsResponse)
_sym_db.RegisterMessage(PullThreadReactionsResponse.ThreadReactionsEntry)

PatchThreadSettingRequest = _reflection.GeneratedProtocolMessageType('PatchThreadSettingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PATCHTHREADSETTINGREQUEST,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PatchThreadSettingRequest)
  ))
_sym_db.RegisterMessage(PatchThreadSettingRequest)

PatchThreadSettingResponse = _reflection.GeneratedProtocolMessageType('PatchThreadSettingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PATCHTHREADSETTINGRESPONSE,
  __module__ = 'thread_pb2'
  # @@protoc_insertion_point(class_scope:PatchThreadSettingResponse)
  ))
_sym_db.RegisterMessage(PatchThreadSettingResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.ss.android.lark.pbZ2git.byted.org/ee/lark/im-protobuf/improto/messages'))
_PULLTHREADREPLIESRESPONSE_MESSAGESENTRY.has_options = True
_PULLTHREADREPLIESRESPONSE_MESSAGESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY.has_options = True
_PULLTHREADREACTIONSRESPONSE_THREADREACTIONSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
