// Code generated by protoc-gen-go.
// source: chats.proto
// DO NOT EDIT!

/*
Package chats is a generated protocol buffer package.

It is generated from these files:
	chats.proto

It has these top-level messages:
	PullChatsRequest
	PullChatsResponse
	PullRecentChatsRequest
	PullRecentChatsResponse
	PullChatsByIdsRequest
	PullChatsByIdsResponse
	PutChatRequest
	PutChatResponse
	PutP2PChatsRequest
	PutP2PChatsResponse
	PatchChatRequest
	PatchChatResponse
	PullChatUsersRequest
	PullChatUsersResponse
	PullChatChattersRequest
	PullChatChattersResponse
	PushChatArchiveRequest
	PushChatArchiveResponse
	PutChatUserRequest
	PutChatUserResponse
	PutChatChatterRequest
	PutChatChatterResponse
	DeleteChatUserRequest
	DeleteChatUserResponse
	DeleteChatChatterRequest
	DeleteChatChatterResponse
	PutChatNameRequest
	PutChatNameResponse
	PatchChatDescriptionRequest
	PatchChatDescriptionResponse
	PatchChatIconRequest
	PatchChatIconResponse
	PatchGroupChatRequest
	PatchGroupChatResponse
	PushChatsRequest
	PushChatsResponse
	PushChatUsersRequest
	PushChatUsersResponse
	PushChatChattersRequest
	PushChatChattersResponse
	PushChatNewMessageCountNotice
	PushChatMessageReadStateNotice
	PatchChatSettingRequest
	PatchChatSettingResponse
	PushChatSettingResponse
	PushChatSettingNotice
	PullChatSettingsRequest
	PullChatSettingsResponse
	PullAllChatSettingsRequest
	PullAllChatSettingsResponse
	PullGroupChatsRequest
	PullGroupChatsResponse
*/
package chats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entities "git.byted.org/ee/lark/im-protobuf/improto/entities"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PullChatsRequest_Type int32

const (
	PullChatsRequest_ALL   PullChatsRequest_Type = 1
	PullChatsRequest_P2P   PullChatsRequest_Type = 2
	PullChatsRequest_GROUP PullChatsRequest_Type = 3
)

var PullChatsRequest_Type_name = map[int32]string{
	1: "ALL",
	2: "P2P",
	3: "GROUP",
}
var PullChatsRequest_Type_value = map[string]int32{
	"ALL":   1,
	"P2P":   2,
	"GROUP": 3,
}

func (x PullChatsRequest_Type) Enum() *PullChatsRequest_Type {
	p := new(PullChatsRequest_Type)
	*p = x
	return p
}
func (x PullChatsRequest_Type) String() string {
	return proto.EnumName(PullChatsRequest_Type_name, int32(x))
}
func (x *PullChatsRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PullChatsRequest_Type_value, data, "PullChatsRequest_Type")
	if err != nil {
		return err
	}
	*x = PullChatsRequest_Type(value)
	return nil
}
func (PullChatsRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PatchGroupChatRequest_UpdateFields int32

const (
	PatchGroupChatRequest_NAME               PatchGroupChatRequest_UpdateFields = 1
	PatchGroupChatRequest_ICON_KEY           PatchGroupChatRequest_UpdateFields = 2
	PatchGroupChatRequest_DESCRIPTION        PatchGroupChatRequest_UpdateFields = 3
	PatchGroupChatRequest_ANNOUNCEMENT       PatchGroupChatRequest_UpdateFields = 4
	PatchGroupChatRequest_OWNER_ID           PatchGroupChatRequest_UpdateFields = 5
	PatchGroupChatRequest_MEMBER_COUNT       PatchGroupChatRequest_UpdateFields = 6
	PatchGroupChatRequest_IS_ARCHIVE         PatchGroupChatRequest_UpdateFields = 7
	PatchGroupChatRequest_IS_PUBLIC          PatchGroupChatRequest_UpdateFields = 8
	PatchGroupChatRequest_IS_INNER           PatchGroupChatRequest_UpdateFields = 9
	PatchGroupChatRequest_ORGANIZATION_ID    PatchGroupChatRequest_UpdateFields = 10
	PatchGroupChatRequest_IS_GROUP_COMPANIES PatchGroupChatRequest_UpdateFields = 11
	PatchGroupChatRequest_GROUP_COMPANIES_ID PatchGroupChatRequest_UpdateFields = 12
)

var PatchGroupChatRequest_UpdateFields_name = map[int32]string{
	1:  "NAME",
	2:  "ICON_KEY",
	3:  "DESCRIPTION",
	4:  "ANNOUNCEMENT",
	5:  "OWNER_ID",
	6:  "MEMBER_COUNT",
	7:  "IS_ARCHIVE",
	8:  "IS_PUBLIC",
	9:  "IS_INNER",
	10: "ORGANIZATION_ID",
	11: "IS_GROUP_COMPANIES",
	12: "GROUP_COMPANIES_ID",
}
var PatchGroupChatRequest_UpdateFields_value = map[string]int32{
	"NAME":               1,
	"ICON_KEY":           2,
	"DESCRIPTION":        3,
	"ANNOUNCEMENT":       4,
	"OWNER_ID":           5,
	"MEMBER_COUNT":       6,
	"IS_ARCHIVE":         7,
	"IS_PUBLIC":          8,
	"IS_INNER":           9,
	"ORGANIZATION_ID":    10,
	"IS_GROUP_COMPANIES": 11,
	"GROUP_COMPANIES_ID": 12,
}

func (x PatchGroupChatRequest_UpdateFields) Enum() *PatchGroupChatRequest_UpdateFields {
	p := new(PatchGroupChatRequest_UpdateFields)
	*p = x
	return p
}
func (x PatchGroupChatRequest_UpdateFields) String() string {
	return proto.EnumName(PatchGroupChatRequest_UpdateFields_name, int32(x))
}
func (x *PatchGroupChatRequest_UpdateFields) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PatchGroupChatRequest_UpdateFields_value, data, "PatchGroupChatRequest_UpdateFields")
	if err != nil {
		return err
	}
	*x = PatchGroupChatRequest_UpdateFields(value)
	return nil
}
func (PatchGroupChatRequest_UpdateFields) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{32, 0}
}

type PushChatUsersRequest_Type int32

const (
	PushChatUsersRequest_ADD_USER    PushChatUsersRequest_Type = 1
	PushChatUsersRequest_DELETE_USER PushChatUsersRequest_Type = 2
)

var PushChatUsersRequest_Type_name = map[int32]string{
	1: "ADD_USER",
	2: "DELETE_USER",
}
var PushChatUsersRequest_Type_value = map[string]int32{
	"ADD_USER":    1,
	"DELETE_USER": 2,
}

func (x PushChatUsersRequest_Type) Enum() *PushChatUsersRequest_Type {
	p := new(PushChatUsersRequest_Type)
	*p = x
	return p
}
func (x PushChatUsersRequest_Type) String() string {
	return proto.EnumName(PushChatUsersRequest_Type_name, int32(x))
}
func (x *PushChatUsersRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PushChatUsersRequest_Type_value, data, "PushChatUsersRequest_Type")
	if err != nil {
		return err
	}
	*x = PushChatUsersRequest_Type(value)
	return nil
}
func (PushChatUsersRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{36, 0}
}

type PushChatChattersRequest_Type int32

const (
	PushChatChattersRequest_ADD_CHATTER    PushChatChattersRequest_Type = 1
	PushChatChattersRequest_DELETE_CHATTER PushChatChattersRequest_Type = 2
)

var PushChatChattersRequest_Type_name = map[int32]string{
	1: "ADD_CHATTER",
	2: "DELETE_CHATTER",
}
var PushChatChattersRequest_Type_value = map[string]int32{
	"ADD_CHATTER":    1,
	"DELETE_CHATTER": 2,
}

func (x PushChatChattersRequest_Type) Enum() *PushChatChattersRequest_Type {
	p := new(PushChatChattersRequest_Type)
	*p = x
	return p
}
func (x PushChatChattersRequest_Type) String() string {
	return proto.EnumName(PushChatChattersRequest_Type_name, int32(x))
}
func (x *PushChatChattersRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PushChatChattersRequest_Type_value, data, "PushChatChattersRequest_Type")
	if err != nil {
		return err
	}
	*x = PushChatChattersRequest_Type(value)
	return nil
}
func (PushChatChattersRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{38, 0}
}

type PullGroupChatsRequest_Type int32

const (
	PullGroupChatsRequest_MANAGE PullGroupChatsRequest_Type = 1
	PullGroupChatsRequest_JOIN   PullGroupChatsRequest_Type = 2
)

var PullGroupChatsRequest_Type_name = map[int32]string{
	1: "MANAGE",
	2: "JOIN",
}
var PullGroupChatsRequest_Type_value = map[string]int32{
	"MANAGE": 1,
	"JOIN":   2,
}

func (x PullGroupChatsRequest_Type) Enum() *PullGroupChatsRequest_Type {
	p := new(PullGroupChatsRequest_Type)
	*p = x
	return p
}
func (x PullGroupChatsRequest_Type) String() string {
	return proto.EnumName(PullGroupChatsRequest_Type_name, int32(x))
}
func (x *PullGroupChatsRequest_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PullGroupChatsRequest_Type_value, data, "PullGroupChatsRequest_Type")
	if err != nil {
		return err
	}
	*x = PullGroupChatsRequest_Type(value)
	return nil
}
func (PullGroupChatsRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{50, 0}
}

// 拉取最近的会话列表
type PullChatsRequest struct {
	UpdateTime       *int64                 `protobuf:"varint,1,opt,name=update_time,json=updateTime,def=0" json:"update_time,omitempty"`
	Count            *int32                 `protobuf:"varint,2,opt,name=count,def=20" json:"count,omitempty"`
	Type             *PullChatsRequest_Type `protobuf:"varint,3,opt,name=type,enum=PullChatsRequest_Type,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PullChatsRequest) Reset()                    { *m = PullChatsRequest{} }
func (m *PullChatsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullChatsRequest) ProtoMessage()               {}
func (*PullChatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_PullChatsRequest_UpdateTime int64 = 0
const Default_PullChatsRequest_Count int32 = 20
const Default_PullChatsRequest_Type PullChatsRequest_Type = PullChatsRequest_ALL

func (m *PullChatsRequest) GetUpdateTime() int64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return Default_PullChatsRequest_UpdateTime
}

func (m *PullChatsRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_PullChatsRequest_Count
}

func (m *PullChatsRequest) GetType() PullChatsRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_PullChatsRequest_Type
}

type PullChatsResponse struct {
	Chats            map[string]*entities.Chat    `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages         map[string]*entities.Message `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MessagePositions map[string]int32             `protobuf:"bytes,3,rep,name=message_positions,json=messagePositions" json:"message_positions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	OrderedChatIds   []string                     `protobuf:"bytes,4,rep,name=ordered_chat_ids,json=orderedChatIds" json:"ordered_chat_ids,omitempty"`
	HasMore          *bool                        `protobuf:"varint,5,opt,name=has_more,json=hasMore,def=0" json:"has_more,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PullChatsResponse) Reset()                    { *m = PullChatsResponse{} }
func (m *PullChatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullChatsResponse) ProtoMessage()               {}
func (*PullChatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_PullChatsResponse_HasMore bool = false

func (m *PullChatsResponse) GetChats() map[string]*entities.Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

func (m *PullChatsResponse) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PullChatsResponse) GetMessagePositions() map[string]int32 {
	if m != nil {
		return m.MessagePositions
	}
	return nil
}

func (m *PullChatsResponse) GetOrderedChatIds() []string {
	if m != nil {
		return m.OrderedChatIds
	}
	return nil
}

func (m *PullChatsResponse) GetHasMore() bool {
	if m != nil && m.HasMore != nil {
		return *m.HasMore
	}
	return Default_PullChatsResponse_HasMore
}

// 获取当前用户最近的会话
type PullRecentChatsRequest struct {
	// 用于请求比此时间戳更新的会话，如果返回的数据量＝count，则说明 has more
	// 此时客户端应该舍弃之前旧的 chat，重新按新的数据最后一条开始翻页获取会话
	NewUpdateTime *int64 `protobuf:"varint,1,opt,name=new_update_time,json=newUpdateTime,def=0" json:"new_update_time,omitempty"`
	// 用于请求比此时间戳更旧的会话
	MoreUpdateTime   *int64 `protobuf:"varint,2,opt,name=more_update_time,json=moreUpdateTime,def=0" json:"more_update_time,omitempty"`
	Count            *int32 `protobuf:"varint,3,opt,name=count,def=20" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PullRecentChatsRequest) Reset()                    { *m = PullRecentChatsRequest{} }
func (m *PullRecentChatsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullRecentChatsRequest) ProtoMessage()               {}
func (*PullRecentChatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_PullRecentChatsRequest_NewUpdateTime int64 = 0
const Default_PullRecentChatsRequest_MoreUpdateTime int64 = 0
const Default_PullRecentChatsRequest_Count int32 = 20

func (m *PullRecentChatsRequest) GetNewUpdateTime() int64 {
	if m != nil && m.NewUpdateTime != nil {
		return *m.NewUpdateTime
	}
	return Default_PullRecentChatsRequest_NewUpdateTime
}

func (m *PullRecentChatsRequest) GetMoreUpdateTime() int64 {
	if m != nil && m.MoreUpdateTime != nil {
		return *m.MoreUpdateTime
	}
	return Default_PullRecentChatsRequest_MoreUpdateTime
}

func (m *PullRecentChatsRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_PullRecentChatsRequest_Count
}

type PullRecentChatsResponse struct {
	Chats            map[string]*entities.Chat    `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages         map[string]*entities.Message `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MessagePositions map[string]int32             `protobuf:"bytes,3,rep,name=message_positions,json=messagePositions" json:"message_positions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	OrderedChatIds   []string                     `protobuf:"bytes,4,rep,name=ordered_chat_ids,json=orderedChatIds" json:"ordered_chat_ids,omitempty"`
	HasMore          *bool                        `protobuf:"varint,5,opt,name=has_more,json=hasMore,def=0" json:"has_more,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PullRecentChatsResponse) Reset()                    { *m = PullRecentChatsResponse{} }
func (m *PullRecentChatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullRecentChatsResponse) ProtoMessage()               {}
func (*PullRecentChatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

const Default_PullRecentChatsResponse_HasMore bool = false

func (m *PullRecentChatsResponse) GetChats() map[string]*entities.Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

func (m *PullRecentChatsResponse) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PullRecentChatsResponse) GetMessagePositions() map[string]int32 {
	if m != nil {
		return m.MessagePositions
	}
	return nil
}

func (m *PullRecentChatsResponse) GetOrderedChatIds() []string {
	if m != nil {
		return m.OrderedChatIds
	}
	return nil
}

func (m *PullRecentChatsResponse) GetHasMore() bool {
	if m != nil && m.HasMore != nil {
		return *m.HasMore
	}
	return Default_PullRecentChatsResponse_HasMore
}

// 会话 mget
type PullChatsByIdsRequest struct {
	ChatIds          []string `protobuf:"bytes,1,rep,name=chat_ids,json=chatIds" json:"chat_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullChatsByIdsRequest) Reset()                    { *m = PullChatsByIdsRequest{} }
func (m *PullChatsByIdsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullChatsByIdsRequest) ProtoMessage()               {}
func (*PullChatsByIdsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PullChatsByIdsRequest) GetChatIds() []string {
	if m != nil {
		return m.ChatIds
	}
	return nil
}

type PullChatsByIdsResponse struct {
	Chats            map[string]*entities.Chat `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *PullChatsByIdsResponse) Reset()                    { *m = PullChatsByIdsResponse{} }
func (m *PullChatsByIdsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullChatsByIdsResponse) ProtoMessage()               {}
func (*PullChatsByIdsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PullChatsByIdsResponse) GetChats() map[string]*entities.Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

// 创建新的 Chat
type PutChatRequest struct {
	Type             *entities.Chat_Type `protobuf:"varint,1,req,name=type,enum=Chat_Type" json:"type,omitempty"`
	UserIds          []string            `protobuf:"bytes,2,rep,name=user_ids,json=userIds" json:"user_ids,omitempty"`
	GroupName        *string             `protobuf:"bytes,3,opt,name=group_name,json=groupName,def=" json:"group_name,omitempty"`
	GroupDesc        *string             `protobuf:"bytes,4,opt,name=group_desc,json=groupDesc,def=" json:"group_desc,omitempty"`
	IsPublic         *bool               `protobuf:"varint,5,opt,name=is_public,json=isPublic,def=0" json:"is_public,omitempty"`
	ChatterIds       []string            `protobuf:"bytes,6,rep,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
	OrganizationId   *string             `protobuf:"bytes,7,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	FromChatId       *string             `protobuf:"bytes,8,opt,name=from_chat_id,json=fromChatId" json:"from_chat_id,omitempty"`
	InitMessageIds   []string            `protobuf:"bytes,9,rep,name=init_message_ids,json=initMessageIds" json:"init_message_ids,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PutChatRequest) Reset()                    { *m = PutChatRequest{} }
func (m *PutChatRequest) String() string            { return proto.CompactTextString(m) }
func (*PutChatRequest) ProtoMessage()               {}
func (*PutChatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_PutChatRequest_IsPublic bool = false

func (m *PutChatRequest) GetType() entities.Chat_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return entities.Chat_P2P
}

func (m *PutChatRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *PutChatRequest) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *PutChatRequest) GetGroupDesc() string {
	if m != nil && m.GroupDesc != nil {
		return *m.GroupDesc
	}
	return ""
}

func (m *PutChatRequest) GetIsPublic() bool {
	if m != nil && m.IsPublic != nil {
		return *m.IsPublic
	}
	return Default_PutChatRequest_IsPublic
}

func (m *PutChatRequest) GetChatterIds() []string {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

func (m *PutChatRequest) GetOrganizationId() string {
	if m != nil && m.OrganizationId != nil {
		return *m.OrganizationId
	}
	return ""
}

func (m *PutChatRequest) GetFromChatId() string {
	if m != nil && m.FromChatId != nil {
		return *m.FromChatId
	}
	return ""
}

func (m *PutChatRequest) GetInitMessageIds() []string {
	if m != nil {
		return m.InitMessageIds
	}
	return nil
}

type PutChatResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PutChatResponse) Reset()                    { *m = PutChatResponse{} }
func (m *PutChatResponse) String() string            { return proto.CompactTextString(m) }
func (*PutChatResponse) ProtoMessage()               {}
func (*PutChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PutChatResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

type PutP2PChatsRequest struct {
	ChatterIds       []string `protobuf:"bytes,1,rep,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PutP2PChatsRequest) Reset()                    { *m = PutP2PChatsRequest{} }
func (m *PutP2PChatsRequest) String() string            { return proto.CompactTextString(m) }
func (*PutP2PChatsRequest) ProtoMessage()               {}
func (*PutP2PChatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PutP2PChatsRequest) GetChatterIds() []string {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

type PutP2PChatsResponse struct {
	Chats            map[string]*entities.Chat `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *PutP2PChatsResponse) Reset()                    { *m = PutP2PChatsResponse{} }
func (m *PutP2PChatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PutP2PChatsResponse) ProtoMessage()               {}
func (*PutP2PChatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PutP2PChatsResponse) GetChats() map[string]*entities.Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

// 修改 Chat
type PatchChatRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	IsPublic         *int32  `protobuf:"varint,2,opt,name=is_public,json=isPublic,def=-1" json:"is_public,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PatchChatRequest) Reset()                    { *m = PatchChatRequest{} }
func (m *PatchChatRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchChatRequest) ProtoMessage()               {}
func (*PatchChatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

const Default_PatchChatRequest_IsPublic int32 = -1

func (m *PatchChatRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PatchChatRequest) GetIsPublic() int32 {
	if m != nil && m.IsPublic != nil {
		return *m.IsPublic
	}
	return Default_PatchChatRequest_IsPublic
}

type PatchChatResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PatchChatResponse) Reset()                    { *m = PatchChatResponse{} }
func (m *PatchChatResponse) String() string            { return proto.CompactTextString(m) }
func (*PatchChatResponse) ProtoMessage()               {}
func (*PatchChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PatchChatResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 拉取 Chat 的成员
// [逐渐废弃]加入机器人
type PullChatUsersRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PullChatUsersRequest) Reset()                    { *m = PullChatUsersRequest{} }
func (m *PullChatUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*PullChatUsersRequest) ProtoMessage()               {}
func (*PullChatUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PullChatUsersRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

type PullChatUsersResponse struct {
	Users map[string]*entities.User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bots  map[string]*entities.Bot  `protobuf:"bytes,2,rep,name=bots" json:"bots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 群成员的权值，最先进入的成员权值小
	OrderedWeight    map[string]int64 `protobuf:"bytes,3,rep,name=ordered_weight,json=orderedWeight" json:"ordered_weight,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PullChatUsersResponse) Reset()                    { *m = PullChatUsersResponse{} }
func (m *PullChatUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*PullChatUsersResponse) ProtoMessage()               {}
func (*PullChatUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PullChatUsersResponse) GetUsers() map[string]*entities.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PullChatUsersResponse) GetBots() map[string]*entities.Bot {
	if m != nil {
		return m.Bots
	}
	return nil
}

func (m *PullChatUsersResponse) GetOrderedWeight() map[string]int64 {
	if m != nil {
		return m.OrderedWeight
	}
	return nil
}

// 拉取 Chat 的成员
type PullChatChattersRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PullChatChattersRequest) Reset()                    { *m = PullChatChattersRequest{} }
func (m *PullChatChattersRequest) String() string            { return proto.CompactTextString(m) }
func (*PullChatChattersRequest) ProtoMessage()               {}
func (*PullChatChattersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PullChatChattersRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

type PullChatChattersResponse struct {
	Chatters map[string]*entities.Chatter `protobuf:"bytes,1,rep,name=chatters" json:"chatters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 群成员的权值，最先进入的成员权值小
	OrderedWeight    map[string]int64 `protobuf:"bytes,2,rep,name=ordered_weight,json=orderedWeight" json:"ordered_weight,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PullChatChattersResponse) Reset()                    { *m = PullChatChattersResponse{} }
func (m *PullChatChattersResponse) String() string            { return proto.CompactTextString(m) }
func (*PullChatChattersResponse) ProtoMessage()               {}
func (*PullChatChattersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PullChatChattersResponse) GetChatters() map[string]*entities.Chatter {
	if m != nil {
		return m.Chatters
	}
	return nil
}

func (m *PullChatChattersResponse) GetOrderedWeight() map[string]int64 {
	if m != nil {
		return m.OrderedWeight
	}
	return nil
}

// 会话归档
type PushChatArchiveRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushChatArchiveRequest) Reset()                    { *m = PushChatArchiveRequest{} }
func (m *PushChatArchiveRequest) String() string            { return proto.CompactTextString(m) }
func (*PushChatArchiveRequest) ProtoMessage()               {}
func (*PushChatArchiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PushChatArchiveRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

type PushChatArchiveResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PushChatArchiveResponse) Reset()                    { *m = PushChatArchiveResponse{} }
func (m *PushChatArchiveResponse) String() string            { return proto.CompactTextString(m) }
func (*PushChatArchiveResponse) ProtoMessage()               {}
func (*PushChatArchiveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PushChatArchiveResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 会话增加新的成员
// [逐渐废弃，机器人加入]
type PutChatUserRequest struct {
	ChatId           *string  `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	UserIds          []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds" json:"user_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PutChatUserRequest) Reset()                    { *m = PutChatUserRequest{} }
func (m *PutChatUserRequest) String() string            { return proto.CompactTextString(m) }
func (*PutChatUserRequest) ProtoMessage()               {}
func (*PutChatUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PutChatUserRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutChatUserRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type PutChatUserResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,opt,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PutChatUserResponse) Reset()                    { *m = PutChatUserResponse{} }
func (m *PutChatUserResponse) String() string            { return proto.CompactTextString(m) }
func (*PutChatUserResponse) ProtoMessage()               {}
func (*PutChatUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PutChatUserResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 会话增加新的成员
type PutChatChatterRequest struct {
	ChatId           *string  `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	ChatterIds       []string `protobuf:"bytes,2,rep,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PutChatChatterRequest) Reset()                    { *m = PutChatChatterRequest{} }
func (m *PutChatChatterRequest) String() string            { return proto.CompactTextString(m) }
func (*PutChatChatterRequest) ProtoMessage()               {}
func (*PutChatChatterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PutChatChatterRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutChatChatterRequest) GetChatterIds() []string {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

type PutChatChatterResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,opt,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PutChatChatterResponse) Reset()                    { *m = PutChatChatterResponse{} }
func (m *PutChatChatterResponse) String() string            { return proto.CompactTextString(m) }
func (*PutChatChatterResponse) ProtoMessage()               {}
func (*PutChatChatterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PutChatChatterResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 删除会话的成员
// [逐渐废弃，机器人加入]
type DeleteChatUserRequest struct {
	ChatId           *string  `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	UserIds          []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds" json:"user_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DeleteChatUserRequest) Reset()                    { *m = DeleteChatUserRequest{} }
func (m *DeleteChatUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteChatUserRequest) ProtoMessage()               {}
func (*DeleteChatUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *DeleteChatUserRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *DeleteChatUserRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type DeleteChatUserResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteChatUserResponse) Reset()                    { *m = DeleteChatUserResponse{} }
func (m *DeleteChatUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteChatUserResponse) ProtoMessage()               {}
func (*DeleteChatUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

// 删除会话的成员
type DeleteChatChatterRequest struct {
	ChatId           *string  `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	ChatterIds       []string `protobuf:"bytes,2,rep,name=chatter_ids,json=chatterIds" json:"chatter_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DeleteChatChatterRequest) Reset()                    { *m = DeleteChatChatterRequest{} }
func (m *DeleteChatChatterRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteChatChatterRequest) ProtoMessage()               {}
func (*DeleteChatChatterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *DeleteChatChatterRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *DeleteChatChatterRequest) GetChatterIds() []string {
	if m != nil {
		return m.ChatterIds
	}
	return nil
}

type DeleteChatChatterResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,opt,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *DeleteChatChatterResponse) Reset()                    { *m = DeleteChatChatterResponse{} }
func (m *DeleteChatChatterResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteChatChatterResponse) ProtoMessage()               {}
func (*DeleteChatChatterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *DeleteChatChatterResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 修改会话的名称
type PutChatNameRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutChatNameRequest) Reset()                    { *m = PutChatNameRequest{} }
func (m *PutChatNameRequest) String() string            { return proto.CompactTextString(m) }
func (*PutChatNameRequest) ProtoMessage()               {}
func (*PutChatNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PutChatNameRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PutChatNameRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type PutChatNameResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PutChatNameResponse) Reset()                    { *m = PutChatNameResponse{} }
func (m *PutChatNameResponse) String() string            { return proto.CompactTextString(m) }
func (*PutChatNameResponse) ProtoMessage()               {}
func (*PutChatNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PutChatNameResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 修改会话的描述
// [废弃,由PatchGroupChatRequest替代]
type PatchChatDescriptionRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Description      *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PatchChatDescriptionRequest) Reset()                    { *m = PatchChatDescriptionRequest{} }
func (m *PatchChatDescriptionRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchChatDescriptionRequest) ProtoMessage()               {}
func (*PatchChatDescriptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PatchChatDescriptionRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PatchChatDescriptionRequest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

// [废弃]
type PatchChatDescriptionResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PatchChatDescriptionResponse) Reset()                    { *m = PatchChatDescriptionResponse{} }
func (m *PatchChatDescriptionResponse) String() string            { return proto.CompactTextString(m) }
func (*PatchChatDescriptionResponse) ProtoMessage()               {}
func (*PatchChatDescriptionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *PatchChatDescriptionResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 修改会话的头像
// [废弃,由PatchGroupChatRequest替代]
type PatchChatIconRequest struct {
	ChatId           *string `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	IconData         *string `protobuf:"bytes,2,req,name=icon_data,json=iconData" json:"icon_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PatchChatIconRequest) Reset()                    { *m = PatchChatIconRequest{} }
func (m *PatchChatIconRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchChatIconRequest) ProtoMessage()               {}
func (*PatchChatIconRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PatchChatIconRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PatchChatIconRequest) GetIconData() string {
	if m != nil && m.IconData != nil {
		return *m.IconData
	}
	return ""
}

// [废弃]
type PatchChatIconResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PatchChatIconResponse) Reset()                    { *m = PatchChatIconResponse{} }
func (m *PatchChatIconResponse) String() string            { return proto.CompactTextString(m) }
func (*PatchChatIconResponse) ProtoMessage()               {}
func (*PatchChatIconResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PatchChatIconResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 修改群设置
type PatchGroupChatRequest struct {
	ChatId           *int64                               `protobuf:"varint,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	Name             *string                              `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IconData         *string                              `protobuf:"bytes,3,opt,name=icon_data,json=iconData" json:"icon_data,omitempty"`
	Description      *string                              `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Announcement     *string                              `protobuf:"bytes,5,opt,name=announcement" json:"announcement,omitempty"`
	OwnerId          *int64                               `protobuf:"varint,6,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	MemberCount      *int32                               `protobuf:"varint,7,opt,name=member_count,json=memberCount" json:"member_count,omitempty"`
	IsArchive        *bool                                `protobuf:"varint,8,opt,name=is_archive,json=isArchive,def=0" json:"is_archive,omitempty"`
	IsPublic         *bool                                `protobuf:"varint,9,opt,name=is_public,json=isPublic,def=0" json:"is_public,omitempty"`
	IsInner          *bool                                `protobuf:"varint,10,opt,name=is_inner,json=isInner,def=0" json:"is_inner,omitempty"`
	OrganizationId   *int64                               `protobuf:"varint,11,opt,name=organization_id,json=organizationId,def=0" json:"organization_id,omitempty"`
	IsGroupCompanies *bool                                `protobuf:"varint,12,opt,name=is_group_companies,json=isGroupCompanies,def=0" json:"is_group_companies,omitempty"`
	GroupCompaniesId *int64                               `protobuf:"varint,13,opt,name=group_companies_id,json=groupCompaniesId,def=0" json:"group_companies_id,omitempty"`
	UpdateFields     []PatchGroupChatRequest_UpdateFields `protobuf:"varint,999,rep,name=update_fields,json=updateFields,enum=PatchGroupChatRequest_UpdateFields" json:"update_fields,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *PatchGroupChatRequest) Reset()                    { *m = PatchGroupChatRequest{} }
func (m *PatchGroupChatRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchGroupChatRequest) ProtoMessage()               {}
func (*PatchGroupChatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

const Default_PatchGroupChatRequest_IsArchive bool = false
const Default_PatchGroupChatRequest_IsPublic bool = false
const Default_PatchGroupChatRequest_IsInner bool = false
const Default_PatchGroupChatRequest_OrganizationId int64 = 0
const Default_PatchGroupChatRequest_IsGroupCompanies bool = false
const Default_PatchGroupChatRequest_GroupCompaniesId int64 = 0

func (m *PatchGroupChatRequest) GetChatId() int64 {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return 0
}

func (m *PatchGroupChatRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PatchGroupChatRequest) GetIconData() string {
	if m != nil && m.IconData != nil {
		return *m.IconData
	}
	return ""
}

func (m *PatchGroupChatRequest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *PatchGroupChatRequest) GetAnnouncement() string {
	if m != nil && m.Announcement != nil {
		return *m.Announcement
	}
	return ""
}

func (m *PatchGroupChatRequest) GetOwnerId() int64 {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return 0
}

func (m *PatchGroupChatRequest) GetMemberCount() int32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

func (m *PatchGroupChatRequest) GetIsArchive() bool {
	if m != nil && m.IsArchive != nil {
		return *m.IsArchive
	}
	return Default_PatchGroupChatRequest_IsArchive
}

func (m *PatchGroupChatRequest) GetIsPublic() bool {
	if m != nil && m.IsPublic != nil {
		return *m.IsPublic
	}
	return Default_PatchGroupChatRequest_IsPublic
}

func (m *PatchGroupChatRequest) GetIsInner() bool {
	if m != nil && m.IsInner != nil {
		return *m.IsInner
	}
	return Default_PatchGroupChatRequest_IsInner
}

func (m *PatchGroupChatRequest) GetOrganizationId() int64 {
	if m != nil && m.OrganizationId != nil {
		return *m.OrganizationId
	}
	return Default_PatchGroupChatRequest_OrganizationId
}

func (m *PatchGroupChatRequest) GetIsGroupCompanies() bool {
	if m != nil && m.IsGroupCompanies != nil {
		return *m.IsGroupCompanies
	}
	return Default_PatchGroupChatRequest_IsGroupCompanies
}

func (m *PatchGroupChatRequest) GetGroupCompaniesId() int64 {
	if m != nil && m.GroupCompaniesId != nil {
		return *m.GroupCompaniesId
	}
	return Default_PatchGroupChatRequest_GroupCompaniesId
}

func (m *PatchGroupChatRequest) GetUpdateFields() []PatchGroupChatRequest_UpdateFields {
	if m != nil {
		return m.UpdateFields
	}
	return nil
}

type PatchGroupChatResponse struct {
	Chat             *entities.Chat `protobuf:"bytes,1,req,name=chat" json:"chat,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PatchGroupChatResponse) Reset()                    { *m = PatchGroupChatResponse{} }
func (m *PatchGroupChatResponse) String() string            { return proto.CompactTextString(m) }
func (*PatchGroupChatResponse) ProtoMessage()               {}
func (*PatchGroupChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PatchGroupChatResponse) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

// 服务器下发会话修改消息
type PushChatsRequest struct {
	Chats            map[string]*entities.Chat `protobuf:"bytes,1,rep,name=chats" json:"chats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *PushChatsRequest) Reset()                    { *m = PushChatsRequest{} }
func (m *PushChatsRequest) String() string            { return proto.CompactTextString(m) }
func (*PushChatsRequest) ProtoMessage()               {}
func (*PushChatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PushChatsRequest) GetChats() map[string]*entities.Chat {
	if m != nil {
		return m.Chats
	}
	return nil
}

type PushChatsResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushChatsResponse) Reset()                    { *m = PushChatsResponse{} }
func (m *PushChatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PushChatsResponse) ProtoMessage()               {}
func (*PushChatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

// 服务器下发新的会话成员列表
// [逐渐废弃,机器人加入, 由pushchatchattersrequest代替]
type PushChatUsersRequest struct {
	Type             *PushChatUsersRequest_Type   `protobuf:"varint,1,req,name=type,enum=PushChatUsersRequest_Type" json:"type,omitempty"`
	Chat             *entities.Chat               `protobuf:"bytes,2,req,name=chat" json:"chat,omitempty"`
	Users            map[string]*entities.User    `protobuf:"bytes,3,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages         map[string]*entities.Message `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrderedWeight    map[string]int64             `protobuf:"bytes,5,rep,name=ordered_weight,json=orderedWeight" json:"ordered_weight,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *PushChatUsersRequest) Reset()                    { *m = PushChatUsersRequest{} }
func (m *PushChatUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*PushChatUsersRequest) ProtoMessage()               {}
func (*PushChatUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PushChatUsersRequest) GetType() PushChatUsersRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PushChatUsersRequest_ADD_USER
}

func (m *PushChatUsersRequest) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *PushChatUsersRequest) GetUsers() map[string]*entities.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PushChatUsersRequest) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PushChatUsersRequest) GetOrderedWeight() map[string]int64 {
	if m != nil {
		return m.OrderedWeight
	}
	return nil
}

type PushChatUsersResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushChatUsersResponse) Reset()                    { *m = PushChatUsersResponse{} }
func (m *PushChatUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*PushChatUsersResponse) ProtoMessage()               {}
func (*PushChatUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

// 服务器下发新的会话成员列表
type PushChatChattersRequest struct {
	Type             *PushChatChattersRequest_Type `protobuf:"varint,1,req,name=type,enum=PushChatChattersRequest_Type" json:"type,omitempty"`
	Chat             *entities.Chat                `protobuf:"bytes,2,req,name=chat" json:"chat,omitempty"`
	Chatters         map[string]*entities.Chatter  `protobuf:"bytes,3,rep,name=chatters" json:"chatters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages         map[string]*entities.Message  `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OrderedWeight    map[string]int64              `protobuf:"bytes,5,rep,name=ordered_weight,json=orderedWeight" json:"ordered_weight,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	OperatorId       *string                       `protobuf:"bytes,6,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PushChatChattersRequest) Reset()                    { *m = PushChatChattersRequest{} }
func (m *PushChatChattersRequest) String() string            { return proto.CompactTextString(m) }
func (*PushChatChattersRequest) ProtoMessage()               {}
func (*PushChatChattersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *PushChatChattersRequest) GetType() PushChatChattersRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PushChatChattersRequest_ADD_CHATTER
}

func (m *PushChatChattersRequest) GetChat() *entities.Chat {
	if m != nil {
		return m.Chat
	}
	return nil
}

func (m *PushChatChattersRequest) GetChatters() map[string]*entities.Chatter {
	if m != nil {
		return m.Chatters
	}
	return nil
}

func (m *PushChatChattersRequest) GetMessages() map[string]*entities.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *PushChatChattersRequest) GetOrderedWeight() map[string]int64 {
	if m != nil {
		return m.OrderedWeight
	}
	return nil
}

func (m *PushChatChattersRequest) GetOperatorId() string {
	if m != nil && m.OperatorId != nil {
		return *m.OperatorId
	}
	return ""
}

type PushChatChattersResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushChatChattersResponse) Reset()                    { *m = PushChatChattersResponse{} }
func (m *PushChatChattersResponse) String() string            { return proto.CompactTextString(m) }
func (*PushChatChattersResponse) ProtoMessage()               {}
func (*PushChatChattersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

// 老接口，逐渐废弃
type PushChatNewMessageCountNotice struct {
	ChatId              *string  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	NewMessageCount     *int32   `protobuf:"varint,2,opt,name=new_message_count,json=newMessageCount" json:"new_message_count,omitempty"`
	LastMessagePosition *int32   `protobuf:"varint,3,opt,name=last_message_position,json=lastMessagePosition" json:"last_message_position,omitempty"`
	MessageIds          []string `protobuf:"bytes,4,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	LastMessageId       *string  `protobuf:"bytes,9,opt,name=last_message_id,json=lastMessageId" json:"last_message_id,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *PushChatNewMessageCountNotice) Reset()                    { *m = PushChatNewMessageCountNotice{} }
func (m *PushChatNewMessageCountNotice) String() string            { return proto.CompactTextString(m) }
func (*PushChatNewMessageCountNotice) ProtoMessage()               {}
func (*PushChatNewMessageCountNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *PushChatNewMessageCountNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushChatNewMessageCountNotice) GetNewMessageCount() int32 {
	if m != nil && m.NewMessageCount != nil {
		return *m.NewMessageCount
	}
	return 0
}

func (m *PushChatNewMessageCountNotice) GetLastMessagePosition() int32 {
	if m != nil && m.LastMessagePosition != nil {
		return *m.LastMessagePosition
	}
	return 0
}

func (m *PushChatNewMessageCountNotice) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PushChatNewMessageCountNotice) GetLastMessageId() string {
	if m != nil && m.LastMessageId != nil {
		return *m.LastMessageId
	}
	return ""
}

// 新接口
type PushChatMessageReadStateNotice struct {
	ChatId              *string  `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	NewMessageCount     *int32   `protobuf:"varint,2,opt,name=new_message_count,json=newMessageCount" json:"new_message_count,omitempty"`
	LastMessagePosition *int32   `protobuf:"varint,3,opt,name=last_message_position,json=lastMessagePosition" json:"last_message_position,omitempty"`
	MessageIds          []string `protobuf:"bytes,4,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	LastMessageId       *string  `protobuf:"bytes,9,opt,name=last_message_id,json=lastMessageId" json:"last_message_id,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *PushChatMessageReadStateNotice) Reset()                    { *m = PushChatMessageReadStateNotice{} }
func (m *PushChatMessageReadStateNotice) String() string            { return proto.CompactTextString(m) }
func (*PushChatMessageReadStateNotice) ProtoMessage()               {}
func (*PushChatMessageReadStateNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *PushChatMessageReadStateNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushChatMessageReadStateNotice) GetNewMessageCount() int32 {
	if m != nil && m.NewMessageCount != nil {
		return *m.NewMessageCount
	}
	return 0
}

func (m *PushChatMessageReadStateNotice) GetLastMessagePosition() int32 {
	if m != nil && m.LastMessagePosition != nil {
		return *m.LastMessagePosition
	}
	return 0
}

func (m *PushChatMessageReadStateNotice) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PushChatMessageReadStateNotice) GetLastMessageId() string {
	if m != nil && m.LastMessageId != nil {
		return *m.LastMessageId
	}
	return ""
}

type PatchChatSettingRequest struct {
	ChatId           *string               `protobuf:"bytes,1,req,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	ChatSetting      *entities.ChatSetting `protobuf:"bytes,2,opt,name=chat_setting,json=chatSetting" json:"chat_setting,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PatchChatSettingRequest) Reset()                    { *m = PatchChatSettingRequest{} }
func (m *PatchChatSettingRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchChatSettingRequest) ProtoMessage()               {}
func (*PatchChatSettingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *PatchChatSettingRequest) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PatchChatSettingRequest) GetChatSetting() *entities.ChatSetting {
	if m != nil {
		return m.ChatSetting
	}
	return nil
}

type PatchChatSettingResponse struct {
	ChatId           *string               `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	ChatSetting      *entities.ChatSetting `protobuf:"bytes,2,opt,name=chat_setting,json=chatSetting" json:"chat_setting,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PatchChatSettingResponse) Reset()                    { *m = PatchChatSettingResponse{} }
func (m *PatchChatSettingResponse) String() string            { return proto.CompactTextString(m) }
func (*PatchChatSettingResponse) ProtoMessage()               {}
func (*PatchChatSettingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *PatchChatSettingResponse) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PatchChatSettingResponse) GetChatSetting() *entities.ChatSetting {
	if m != nil {
		return m.ChatSetting
	}
	return nil
}

type PushChatSettingResponse struct {
	ChatId           *string               `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	ChatSetting      *entities.ChatSetting `protobuf:"bytes,2,opt,name=chat_setting,json=chatSetting" json:"chat_setting,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PushChatSettingResponse) Reset()                    { *m = PushChatSettingResponse{} }
func (m *PushChatSettingResponse) String() string            { return proto.CompactTextString(m) }
func (*PushChatSettingResponse) ProtoMessage()               {}
func (*PushChatSettingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *PushChatSettingResponse) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushChatSettingResponse) GetChatSetting() *entities.ChatSetting {
	if m != nil {
		return m.ChatSetting
	}
	return nil
}

type PushChatSettingNotice struct {
	ChatId           *string               `protobuf:"bytes,1,opt,name=chat_id,json=chatId" json:"chat_id,omitempty"`
	ChatSetting      *entities.ChatSetting `protobuf:"bytes,2,opt,name=chat_setting,json=chatSetting" json:"chat_setting,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *PushChatSettingNotice) Reset()                    { *m = PushChatSettingNotice{} }
func (m *PushChatSettingNotice) String() string            { return proto.CompactTextString(m) }
func (*PushChatSettingNotice) ProtoMessage()               {}
func (*PushChatSettingNotice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *PushChatSettingNotice) GetChatId() string {
	if m != nil && m.ChatId != nil {
		return *m.ChatId
	}
	return ""
}

func (m *PushChatSettingNotice) GetChatSetting() *entities.ChatSetting {
	if m != nil {
		return m.ChatSetting
	}
	return nil
}

type PullChatSettingsRequest struct {
	ChatIds          []string `protobuf:"bytes,1,rep,name=chat_ids,json=chatIds" json:"chat_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullChatSettingsRequest) Reset()                    { *m = PullChatSettingsRequest{} }
func (m *PullChatSettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullChatSettingsRequest) ProtoMessage()               {}
func (*PullChatSettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *PullChatSettingsRequest) GetChatIds() []string {
	if m != nil {
		return m.ChatIds
	}
	return nil
}

type PullChatSettingsResponse struct {
	ChatSettings     map[string]*entities.ChatSetting `protobuf:"bytes,1,rep,name=chat_settings,json=chatSettings" json:"chat_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *PullChatSettingsResponse) Reset()                    { *m = PullChatSettingsResponse{} }
func (m *PullChatSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullChatSettingsResponse) ProtoMessage()               {}
func (*PullChatSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *PullChatSettingsResponse) GetChatSettings() map[string]*entities.ChatSetting {
	if m != nil {
		return m.ChatSettings
	}
	return nil
}

// 客户端拉取用户所有的chatSetting，
// 不给update_time,根据user_id拉取群消息设置，只返回数据库中有的chat_id及对应的设置，未会返回的chat_id其消息默认是提醒的
// 给update_time，返回update_time以后有变动的chat_id及对应的设置，未返回的默认设置没有变动
type PullAllChatSettingsRequest struct {
	UpdateTime       *int64 `protobuf:"varint,1,opt,name=update_time,json=updateTime,def=0" json:"update_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PullAllChatSettingsRequest) Reset()                    { *m = PullAllChatSettingsRequest{} }
func (m *PullAllChatSettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullAllChatSettingsRequest) ProtoMessage()               {}
func (*PullAllChatSettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

const Default_PullAllChatSettingsRequest_UpdateTime int64 = 0

func (m *PullAllChatSettingsRequest) GetUpdateTime() int64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return Default_PullAllChatSettingsRequest_UpdateTime
}

type PullAllChatSettingsResponse struct {
	ChatSettings     map[string]*entities.ChatSetting `protobuf:"bytes,1,rep,name=chat_settings,json=chatSettings" json:"chat_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *PullAllChatSettingsResponse) Reset()                    { *m = PullAllChatSettingsResponse{} }
func (m *PullAllChatSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullAllChatSettingsResponse) ProtoMessage()               {}
func (*PullAllChatSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *PullAllChatSettingsResponse) GetChatSettings() map[string]*entities.ChatSetting {
	if m != nil {
		return m.ChatSettings
	}
	return nil
}

type PullGroupChatsRequest struct {
	Type             *PullGroupChatsRequest_Type `protobuf:"varint,1,req,name=type,enum=PullGroupChatsRequest_Type" json:"type,omitempty"`
	UpdateTime       *int64                      `protobuf:"varint,2,opt,name=update_time,json=updateTime,def=0" json:"update_time,omitempty"`
	Count            *int32                      `protobuf:"varint,3,opt,name=count,def=20" json:"count,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PullGroupChatsRequest) Reset()                    { *m = PullGroupChatsRequest{} }
func (m *PullGroupChatsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullGroupChatsRequest) ProtoMessage()               {}
func (*PullGroupChatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

const Default_PullGroupChatsRequest_UpdateTime int64 = 0
const Default_PullGroupChatsRequest_Count int32 = 20

func (m *PullGroupChatsRequest) GetType() PullGroupChatsRequest_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PullGroupChatsRequest_MANAGE
}

func (m *PullGroupChatsRequest) GetUpdateTime() int64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return Default_PullGroupChatsRequest_UpdateTime
}

func (m *PullGroupChatsRequest) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_PullGroupChatsRequest_Count
}

type PullGroupChatsResponse struct {
	ChatIds []string `protobuf:"bytes,1,rep,name=chat_ids,json=chatIds" json:"chat_ids,omitempty"`
	HasMore *bool    `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	// chat_id 与 join_time 对应关系
	ChatJoinTimes map[string]int64 `protobuf:"bytes,3,rep,name=chat_join_times,json=chatJoinTimes" json:"chat_join_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// chat_id 与 create_time 对应关系
	ChatCreateTimes  map[string]int64 `protobuf:"bytes,4,rep,name=chat_create_times,json=chatCreateTimes" json:"chat_create_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PullGroupChatsResponse) Reset()                    { *m = PullGroupChatsResponse{} }
func (m *PullGroupChatsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullGroupChatsResponse) ProtoMessage()               {}
func (*PullGroupChatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *PullGroupChatsResponse) GetChatIds() []string {
	if m != nil {
		return m.ChatIds
	}
	return nil
}

func (m *PullGroupChatsResponse) GetHasMore() bool {
	if m != nil && m.HasMore != nil {
		return *m.HasMore
	}
	return false
}

func (m *PullGroupChatsResponse) GetChatJoinTimes() map[string]int64 {
	if m != nil {
		return m.ChatJoinTimes
	}
	return nil
}

func (m *PullGroupChatsResponse) GetChatCreateTimes() map[string]int64 {
	if m != nil {
		return m.ChatCreateTimes
	}
	return nil
}

func init() {
	proto.RegisterType((*PullChatsRequest)(nil), "PullChatsRequest")
	proto.RegisterType((*PullChatsResponse)(nil), "PullChatsResponse")
	proto.RegisterType((*PullRecentChatsRequest)(nil), "PullRecentChatsRequest")
	proto.RegisterType((*PullRecentChatsResponse)(nil), "PullRecentChatsResponse")
	proto.RegisterType((*PullChatsByIdsRequest)(nil), "PullChatsByIdsRequest")
	proto.RegisterType((*PullChatsByIdsResponse)(nil), "PullChatsByIdsResponse")
	proto.RegisterType((*PutChatRequest)(nil), "PutChatRequest")
	proto.RegisterType((*PutChatResponse)(nil), "PutChatResponse")
	proto.RegisterType((*PutP2PChatsRequest)(nil), "PutP2PChatsRequest")
	proto.RegisterType((*PutP2PChatsResponse)(nil), "PutP2PChatsResponse")
	proto.RegisterType((*PatchChatRequest)(nil), "PatchChatRequest")
	proto.RegisterType((*PatchChatResponse)(nil), "PatchChatResponse")
	proto.RegisterType((*PullChatUsersRequest)(nil), "PullChatUsersRequest")
	proto.RegisterType((*PullChatUsersResponse)(nil), "PullChatUsersResponse")
	proto.RegisterType((*PullChatChattersRequest)(nil), "PullChatChattersRequest")
	proto.RegisterType((*PullChatChattersResponse)(nil), "PullChatChattersResponse")
	proto.RegisterType((*PushChatArchiveRequest)(nil), "PushChatArchiveRequest")
	proto.RegisterType((*PushChatArchiveResponse)(nil), "PushChatArchiveResponse")
	proto.RegisterType((*PutChatUserRequest)(nil), "PutChatUserRequest")
	proto.RegisterType((*PutChatUserResponse)(nil), "PutChatUserResponse")
	proto.RegisterType((*PutChatChatterRequest)(nil), "PutChatChatterRequest")
	proto.RegisterType((*PutChatChatterResponse)(nil), "PutChatChatterResponse")
	proto.RegisterType((*DeleteChatUserRequest)(nil), "DeleteChatUserRequest")
	proto.RegisterType((*DeleteChatUserResponse)(nil), "DeleteChatUserResponse")
	proto.RegisterType((*DeleteChatChatterRequest)(nil), "DeleteChatChatterRequest")
	proto.RegisterType((*DeleteChatChatterResponse)(nil), "DeleteChatChatterResponse")
	proto.RegisterType((*PutChatNameRequest)(nil), "PutChatNameRequest")
	proto.RegisterType((*PutChatNameResponse)(nil), "PutChatNameResponse")
	proto.RegisterType((*PatchChatDescriptionRequest)(nil), "PatchChatDescriptionRequest")
	proto.RegisterType((*PatchChatDescriptionResponse)(nil), "PatchChatDescriptionResponse")
	proto.RegisterType((*PatchChatIconRequest)(nil), "PatchChatIconRequest")
	proto.RegisterType((*PatchChatIconResponse)(nil), "PatchChatIconResponse")
	proto.RegisterType((*PatchGroupChatRequest)(nil), "PatchGroupChatRequest")
	proto.RegisterType((*PatchGroupChatResponse)(nil), "PatchGroupChatResponse")
	proto.RegisterType((*PushChatsRequest)(nil), "PushChatsRequest")
	proto.RegisterType((*PushChatsResponse)(nil), "PushChatsResponse")
	proto.RegisterType((*PushChatUsersRequest)(nil), "PushChatUsersRequest")
	proto.RegisterType((*PushChatUsersResponse)(nil), "PushChatUsersResponse")
	proto.RegisterType((*PushChatChattersRequest)(nil), "PushChatChattersRequest")
	proto.RegisterType((*PushChatChattersResponse)(nil), "PushChatChattersResponse")
	proto.RegisterType((*PushChatNewMessageCountNotice)(nil), "PushChatNewMessageCountNotice")
	proto.RegisterType((*PushChatMessageReadStateNotice)(nil), "PushChatMessageReadStateNotice")
	proto.RegisterType((*PatchChatSettingRequest)(nil), "PatchChatSettingRequest")
	proto.RegisterType((*PatchChatSettingResponse)(nil), "PatchChatSettingResponse")
	proto.RegisterType((*PushChatSettingResponse)(nil), "PushChatSettingResponse")
	proto.RegisterType((*PushChatSettingNotice)(nil), "PushChatSettingNotice")
	proto.RegisterType((*PullChatSettingsRequest)(nil), "PullChatSettingsRequest")
	proto.RegisterType((*PullChatSettingsResponse)(nil), "PullChatSettingsResponse")
	proto.RegisterType((*PullAllChatSettingsRequest)(nil), "PullAllChatSettingsRequest")
	proto.RegisterType((*PullAllChatSettingsResponse)(nil), "PullAllChatSettingsResponse")
	proto.RegisterType((*PullGroupChatsRequest)(nil), "PullGroupChatsRequest")
	proto.RegisterType((*PullGroupChatsResponse)(nil), "PullGroupChatsResponse")
	proto.RegisterEnum("PullChatsRequest_Type", PullChatsRequest_Type_name, PullChatsRequest_Type_value)
	proto.RegisterEnum("PatchGroupChatRequest_UpdateFields", PatchGroupChatRequest_UpdateFields_name, PatchGroupChatRequest_UpdateFields_value)
	proto.RegisterEnum("PushChatUsersRequest_Type", PushChatUsersRequest_Type_name, PushChatUsersRequest_Type_value)
	proto.RegisterEnum("PushChatChattersRequest_Type", PushChatChattersRequest_Type_name, PushChatChattersRequest_Type_value)
	proto.RegisterEnum("PullGroupChatsRequest_Type", PullGroupChatsRequest_Type_name, PullGroupChatsRequest_Type_value)
}

func init() { proto.RegisterFile("chats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x5a, 0xcd, 0x73, 0xdb, 0xc6,
	0x15, 0x17, 0xf8, 0x21, 0x91, 0x8f, 0x14, 0x09, 0xad, 0x6d, 0x09, 0xa6, 0x9c, 0x98, 0x41, 0xda,
	0x44, 0xf1, 0x07, 0x68, 0xd3, 0x4e, 0x9a, 0x68, 0x9a, 0x89, 0x29, 0x8a, 0x91, 0x91, 0x48, 0x24,
	0x03, 0x4a, 0x4d, 0x9a, 0x1e, 0x30, 0x10, 0xb1, 0xa6, 0xd0, 0x88, 0x00, 0x0b, 0x80, 0xd1, 0xa8,
	0xc7, 0x5e, 0x3a, 0xd3, 0x69, 0x7b, 0xe9, 0xad, 0xd3, 0x43, 0x0f, 0x9d, 0xfe, 0x13, 0x9d, 0x1e,
	0x7a, 0xea, 0x1f, 0xd1, 0x53, 0x7b, 0xe9, 0x7f, 0xd0, 0x73, 0x67, 0x77, 0x01, 0x10, 0x9f, 0xa6,
	0xdc, 0xd8, 0x9d, 0x4c, 0xa7, 0x37, 0xe2, 0xe1, 0xbd, 0xb7, 0xef, 0xe3, 0x87, 0xb7, 0x6f, 0xdf,
	0x12, 0x2a, 0xe3, 0x33, 0xcd, 0x75, 0xa4, 0x99, 0x6d, 0xb9, 0x56, 0xa3, 0x86, 0x4d, 0xd7, 0x70,
	0x0d, 0xec, 0x3d, 0x8b, 0x7f, 0xe4, 0x80, 0x1f, 0xce, 0xcf, 0xcf, 0xbb, 0x84, 0x47, 0xc1, 0x3f,
	0x99, 0x63, 0xc7, 0x45, 0x22, 0x54, 0xe6, 0x33, 0x5d, 0x73, 0xb1, 0xea, 0x1a, 0x53, 0x2c, 0x70,
	0x4d, 0x6e, 0x27, 0xbf, 0xcb, 0x3d, 0x50, 0x80, 0x51, 0x8f, 0x8d, 0x29, 0x46, 0x02, 0x14, 0xc7,
	0xd6, 0xdc, 0x74, 0x85, 0x5c, 0x93, 0xdb, 0x29, 0xee, 0xe6, 0xda, 0x0f, 0x14, 0x46, 0x40, 0x2d,
	0x28, 0xb8, 0x97, 0x33, 0x2c, 0xe4, 0x9b, 0xdc, 0x4e, 0xad, 0xbd, 0x29, 0xc5, 0xd5, 0x4b, 0xc7,
	0x97, 0x33, 0xbc, 0x9b, 0xef, 0x1c, 0x1e, 0x2a, 0x94, 0x51, 0x7c, 0x13, 0x0a, 0x84, 0x84, 0xd6,
	0x80, 0x10, 0x79, 0x8e, 0xfc, 0x18, 0xb6, 0x87, 0x7c, 0x0e, 0x95, 0xa1, 0x78, 0xa0, 0x0c, 0x4e,
	0x86, 0x7c, 0x5e, 0xfc, 0x57, 0x1e, 0x36, 0x42, 0x9a, 0x9c, 0x99, 0x65, 0x3a, 0x18, 0x3d, 0x82,
	0x22, 0xf5, 0x4e, 0xe0, 0x9a, 0xf9, 0x9d, 0x4a, 0xfb, 0x35, 0x29, 0xc1, 0x22, 0xd1, 0xa7, 0x9e,
	0xe9, 0xda, 0x97, 0x0a, 0xe3, 0x45, 0xdf, 0x87, 0xd2, 0x14, 0x3b, 0x8e, 0x36, 0xc1, 0x8e, 0x90,
	0xa3, 0x72, 0xcd, 0x14, 0xb9, 0x23, 0x8f, 0x85, 0x89, 0x06, 0x12, 0xe8, 0x04, 0x36, 0xbc, 0xdf,
	0xea, 0xcc, 0x72, 0x0c, 0xd7, 0xb0, 0x4c, 0x47, 0xc8, 0x53, 0x35, 0x3b, 0xd9, 0x6a, 0x86, 0x3e,
	0x2b, 0x53, 0xc7, 0x4f, 0x63, 0x64, 0xb4, 0x03, 0xbc, 0x65, 0xeb, 0xd8, 0xc6, 0xba, 0x4a, 0xac,
	0x54, 0x0d, 0xdd, 0x11, 0x0a, 0xcd, 0xfc, 0x4e, 0x59, 0xa9, 0x79, 0x74, 0xa2, 0x57, 0xd6, 0x1d,
	0xd4, 0x84, 0xd2, 0x99, 0xe6, 0xa8, 0x53, 0xcb, 0xc6, 0x42, 0xb1, 0xc9, 0xed, 0x94, 0x76, 0x8b,
	0xcf, 0xb4, 0x73, 0x07, 0x2b, 0x6b, 0x67, 0x9a, 0x73, 0x64, 0xd9, 0xb8, 0xf1, 0x11, 0xc0, 0xc2,
	0x6b, 0xc4, 0x43, 0xfe, 0x2b, 0x7c, 0x49, 0xb3, 0x58, 0x56, 0xc8, 0x4f, 0xb4, 0x0d, 0xc5, 0xaf,
	0xb5, 0xf3, 0x39, 0xa6, 0xb9, 0xab, 0xb4, 0x8b, 0x34, 0x46, 0x0a, 0xa3, 0xed, 0xe6, 0xde, 0xe7,
	0x1a, 0x3d, 0x58, 0x8f, 0xb8, 0x9f, 0xa2, 0xe3, 0xf5, 0xa8, 0x8e, 0x92, 0xef, 0x68, 0x58, 0x4d,
	0x17, 0x6e, 0xa4, 0xba, 0x9f, 0xa2, 0xee, 0x7a, 0x58, 0x5d, 0x31, 0xa4, 0x44, 0xfc, 0x05, 0x07,
	0x9b, 0x24, 0xac, 0x0a, 0x1e, 0x63, 0xd3, 0x8d, 0xe0, 0xf4, 0x1d, 0xa8, 0x9b, 0xf8, 0x42, 0x4d,
	0xc5, 0xea, 0xba, 0x89, 0x2f, 0x4e, 0x16, 0x70, 0xbd, 0x0b, 0x3c, 0x09, 0x58, 0x84, 0x37, 0xe7,
	0xf3, 0xd6, 0xc8, 0xab, 0x93, 0x14, 0x6c, 0xe7, 0x63, 0xd8, 0x16, 0x7f, 0x5d, 0x80, 0xad, 0x84,
	0x31, 0x1e, 0x16, 0x3f, 0x88, 0x62, 0xf1, 0x4d, 0x29, 0x83, 0x31, 0x05, 0x91, 0x7b, 0x09, 0x44,
	0xbe, 0x95, 0x29, 0x9d, 0x85, 0xcb, 0x1f, 0x65, 0xe3, 0x52, 0x5a, 0xa6, 0xec, 0xff, 0xe8, 0xfc,
	0x4f, 0xd1, 0xd9, 0x86, 0x1b, 0xc1, 0x37, 0xbf, 0x77, 0x29, 0xeb, 0x01, 0x36, 0x6f, 0x42, 0x29,
	0x88, 0x14, 0x47, 0x23, 0xb5, 0x36, 0x66, 0x21, 0x12, 0x7f, 0xe3, 0x21, 0x3a, 0x2c, 0xe4, 0x61,
	0xe8, 0xfd, 0x28, 0x86, 0x44, 0x29, 0x9d, 0x2f, 0x09, 0xa1, 0x6f, 0x1c, 0x55, 0xf1, 0xaf, 0x39,
	0xa8, 0x0d, 0xe7, 0x14, 0x1f, 0xbe, 0x0f, 0xaf, 0x7b, 0x95, 0x9c, 0x6b, 0xe6, 0x76, 0x6a, 0x6d,
	0xa0, 0x22, 0xb4, 0x7a, 0xb3, 0xc2, 0x4d, 0x7c, 0x9c, 0x3b, 0xd8, 0xa6, 0x3e, 0xe6, 0x98, 0x8f,
	0xe4, 0x99, 0xc0, 0xe0, 0x36, 0xc0, 0xc4, 0xb6, 0xe6, 0x33, 0xd5, 0xd4, 0xa6, 0x6c, 0x2b, 0x28,
	0xef, 0xae, 0x28, 0x65, 0x4a, 0xeb, 0x6b, 0x53, 0xbc, 0x60, 0xd0, 0xb1, 0x33, 0x16, 0x0a, 0x11,
	0x86, 0x7d, 0xec, 0x8c, 0x91, 0x08, 0x65, 0xc3, 0x51, 0x67, 0xf3, 0xd3, 0x73, 0x63, 0x1c, 0x45,
	0x52, 0xc9, 0x70, 0x86, 0x94, 0x8c, 0x6e, 0xb3, 0xcd, 0xcd, 0xf5, 0x6c, 0x58, 0xa5, 0x36, 0x80,
	0x47, 0x22, 0x66, 0xbc, 0x0d, 0x75, 0xcb, 0x9e, 0x68, 0xa6, 0xf1, 0x53, 0x8d, 0x24, 0x58, 0x35,
	0x74, 0x61, 0x8d, 0xc6, 0xa4, 0x16, 0x26, 0xcb, 0x3a, 0x6a, 0x42, 0xf5, 0x99, 0x6d, 0x4d, 0x7d,
	0x74, 0x0b, 0x25, 0xca, 0x05, 0x84, 0xc6, 0x90, 0x4d, 0x3e, 0x01, 0xc3, 0x34, 0x5c, 0xd5, 0xff,
	0xc8, 0xc8, 0x82, 0x65, 0xf6, 0x09, 0x10, 0xba, 0x07, 0x25, 0x92, 0xdf, 0x7b, 0x50, 0x0f, 0x02,
	0xe9, 0xe5, 0xf5, 0x26, 0x14, 0x88, 0x66, 0x1a, 0xc9, 0x20, 0xf8, 0x94, 0x24, 0xbe, 0x0b, 0x68,
	0x38, 0x77, 0x87, 0xed, 0x61, 0xa4, 0xb4, 0xc5, 0x3c, 0xe3, 0xe2, 0x9e, 0x89, 0xbf, 0xe2, 0xe0,
	0x5a, 0x44, 0xce, 0x5b, 0xe9, 0xdd, 0x28, 0x82, 0x6e, 0x4b, 0x29, 0x4c, 0xaf, 0x02, 0x3e, 0x87,
	0xc0, 0x0f, 0x35, 0x77, 0x7c, 0x16, 0xc6, 0xcf, 0x16, 0xac, 0xf9, 0xf1, 0x24, 0x8e, 0x97, 0x95,
	0x55, 0xf6, 0x09, 0xa0, 0xdb, 0xe1, 0xdc, 0x7a, 0x0d, 0xc4, 0xfd, 0x87, 0x8b, 0xc4, 0x8a, 0x12,
	0x6c, 0x84, 0xb4, 0x2d, 0x0f, 0x62, 0x0b, 0xae, 0xfb, 0x5f, 0xca, 0x89, 0x83, 0x6d, 0x67, 0x99,
	0x05, 0xe2, 0x6f, 0xf3, 0x8b, 0x0f, 0xd7, 0x93, 0xf0, 0x56, 0xf9, 0x1e, 0x14, 0x09, 0x88, 0xfd,
	0x00, 0xbe, 0x21, 0xa5, 0xb2, 0x49, 0xf4, 0xc9, 0x0b, 0x21, 0xe5, 0x47, 0x8f, 0xa1, 0x70, 0x6a,
	0xb9, 0xc9, 0x96, 0x22, 0x2a, 0xb7, 0x67, 0xf9, 0x91, 0xa7, 0xdc, 0x68, 0x08, 0x7e, 0x05, 0x55,
	0x2f, 0xb0, 0x31, 0x39, 0x73, 0xbd, 0x9a, 0xfd, 0x4e, 0x86, 0xfc, 0x80, 0x31, 0x7f, 0x4e, 0x79,
	0x99, 0xa2, 0x75, 0x2b, 0x4c, 0x23, 0xa9, 0x5c, 0x18, 0x77, 0x95, 0x54, 0x12, 0xee, 0x70, 0x61,
	0xfc, 0x10, 0xca, 0x81, 0x95, 0x29, 0xf2, 0x8d, 0xa8, 0x7c, 0x81, 0xb8, 0x14, 0x16, 0x7f, 0x02,
	0x28, 0x69, 0xe4, 0xb2, 0xa2, 0x9a, 0x8f, 0x16, 0xd5, 0x2d, 0xdf, 0xf9, 0x2e, 0x43, 0xfc, 0xf2,
	0x84, 0xfe, 0x39, 0x07, 0x42, 0x52, 0xc8, 0xcb, 0x69, 0x97, 0x15, 0x63, 0x77, 0x91, 0xd6, 0xb7,
	0xa5, 0x2c, 0x66, 0xc9, 0x27, 0x78, 0x1b, 0xac, 0x2f, 0x88, 0x46, 0x89, 0x4c, 0xb1, 0x4c, 0xdf,
	0xcb, 0x56, 0xb5, 0x3c, 0x59, 0x3d, 0x58, 0x8f, 0xac, 0x77, 0x95, 0xbd, 0xcc, 0x13, 0x78, 0xb9,
	0x31, 0x7f, 0x48, 0xf6, 0x24, 0x87, 0x7e, 0x70, 0x1d, 0x7b, 0x7c, 0x66, 0x7c, 0x8d, 0x97, 0x86,
	0xfc, 0x31, 0x49, 0x53, 0x4c, 0x64, 0xf9, 0xa7, 0xfa, 0x94, 0xd6, 0x3b, 0x1f, 0xd8, 0x4b, 0x4b,
	0x45, 0xf6, 0x1e, 0x23, 0x3e, 0xa0, 0x15, 0x70, 0xa1, 0x29, 0xb1, 0x36, 0x17, 0x5f, 0xfb, 0x33,
	0xf2, 0xd1, 0xbb, 0xa1, 0x54, 0x5d, 0xa1, 0x52, 0x45, 0xea, 0x70, 0x2e, 0x51, 0x87, 0x1f, 0x91,
	0xb8, 0x45, 0x55, 0x2e, 0xb7, 0xe3, 0x53, 0xb8, 0xb1, 0x8f, 0xcf, 0xb1, 0x8b, 0x5f, 0x46, 0x18,
	0x04, 0xd8, 0x8c, 0x2b, 0x63, 0x16, 0x88, 0xc7, 0x20, 0x2c, 0xde, 0xbc, 0x34, 0x8f, 0xdf, 0x83,
	0x9b, 0x29, 0x5a, 0x97, 0x3b, 0xdd, 0x09, 0x12, 0x4f, 0x1a, 0x80, 0xa5, 0x76, 0x20, 0x28, 0xd0,
	0xde, 0x21, 0x47, 0xa9, 0xf4, 0x77, 0x28, 0xe3, 0x4c, 0xc5, 0x72, 0xb4, 0x7d, 0x01, 0xdb, 0xc1,
	0x46, 0x42, 0xda, 0x0a, 0xdb, 0x98, 0x91, 0x1d, 0x7f, 0xe9, 0xea, 0x4d, 0xa8, 0xe8, 0x0b, 0x76,
	0xcf, 0x88, 0x30, 0x49, 0xfc, 0x00, 0x6e, 0xa5, 0x6b, 0x5e, 0x6e, 0xd4, 0x21, 0x5c, 0x0f, 0x44,
	0xe5, 0xf1, 0x15, 0xac, 0xd9, 0x86, 0xb2, 0x31, 0xb6, 0x4c, 0x55, 0xd7, 0x5c, 0xcd, 0xb3, 0xa5,
	0x44, 0x08, 0xfb, 0x9a, 0xab, 0xd1, 0x16, 0x34, 0xaa, 0x6d, 0xb9, 0x05, 0xbf, 0x5c, 0xf5, 0x84,
	0x0e, 0x48, 0xbf, 0x95, 0xb9, 0x67, 0x93, 0x1a, 0x91, 0xcc, 0x07, 0xe7, 0xe7, 0x23, 0x6a, 0x17,
	0x6d, 0xf2, 0x16, 0x76, 0xc5, 0x43, 0x48, 0x5b, 0xbc, 0x48, 0x08, 0x91, 0x08, 0x55, 0xcd, 0x34,
	0xad, 0xb9, 0x39, 0xc6, 0x53, 0x6c, 0xba, 0xb4, 0xcb, 0x2b, 0x2b, 0x11, 0x1a, 0x01, 0xbe, 0x75,
	0x61, 0x52, 0x30, 0x0a, 0xab, 0xd4, 0xa0, 0x35, 0xfa, 0x2c, 0xeb, 0xe8, 0x0d, 0xa8, 0x4e, 0xf1,
	0xf4, 0x14, 0xdb, 0x2a, 0x3b, 0xad, 0xad, 0xd1, 0xe6, 0xbc, 0xc2, 0x68, 0x5d, 0x3a, 0x8b, 0xf8,
	0x0e, 0x80, 0xe1, 0xa8, 0x1a, 0xab, 0x4e, 0xb4, 0xa9, 0x0b, 0xba, 0xc8, 0xb2, 0xe1, 0x78, 0x55,
	0x2b, 0xda, 0x6a, 0x96, 0xd3, 0x5b, 0xcd, 0x26, 0x94, 0x0c, 0x47, 0x35, 0x4c, 0x13, 0xdb, 0x02,
	0x44, 0xce, 0x35, 0x86, 0x23, 0x13, 0x2a, 0xba, 0x93, 0xec, 0x35, 0x2b, 0xc1, 0x09, 0x33, 0xd6,
	0x6e, 0x3e, 0x02, 0x64, 0x38, 0x2a, 0x6b, 0x80, 0xc7, 0xd6, 0x74, 0xa6, 0x99, 0x06, 0x76, 0x84,
	0x6a, 0x58, 0x2f, 0x6f, 0x38, 0x2c, 0x39, 0xfe, 0x6b, 0xd4, 0x02, 0x14, 0x93, 0x20, 0x6b, 0xac,
	0xfb, 0x6b, 0xf0, 0x93, 0x08, 0xbb, 0xac, 0x23, 0x19, 0xd6, 0xbd, 0xf3, 0xee, 0x33, 0x03, 0x9f,
	0xeb, 0x8e, 0xf0, 0xcf, 0xb5, 0x66, 0x7e, 0xa7, 0x46, 0x8e, 0xa6, 0x69, 0xb9, 0x97, 0xd8, 0x11,
	0xf8, 0x63, 0xca, 0xab, 0x54, 0xe7, 0xa1, 0x27, 0xf1, 0x6f, 0x1c, 0x54, 0xc3, 0xaf, 0x51, 0x09,
	0x0a, 0xfd, 0xce, 0x51, 0x8f, 0xe7, 0x50, 0x15, 0x4a, 0x72, 0x77, 0xd0, 0x57, 0x3f, 0xed, 0xfd,
	0x90, 0xcf, 0xa1, 0x3a, 0x54, 0xf6, 0x7b, 0xa3, 0xae, 0x22, 0x0f, 0x8f, 0xe5, 0x41, 0x9f, 0xcf,
	0x23, 0x1e, 0xaa, 0x9d, 0x7e, 0x7f, 0x70, 0xd2, 0xef, 0xf6, 0x8e, 0x7a, 0xfd, 0x63, 0xbe, 0x40,
	0x04, 0x06, 0x9f, 0xf7, 0x7b, 0x8a, 0x2a, 0xef, 0xf3, 0x45, 0xf2, 0xfe, 0xa8, 0x77, 0xb4, 0xd7,
	0x53, 0xd4, 0xee, 0xe0, 0xa4, 0x7f, 0xcc, 0xaf, 0xa2, 0x1a, 0x80, 0x3c, 0x52, 0x3b, 0x4a, 0xf7,
	0xa9, 0xfc, 0x83, 0x1e, 0xbf, 0x86, 0xd6, 0xa1, 0x2c, 0x8f, 0xd4, 0xe1, 0xc9, 0xde, 0xa1, 0xdc,
	0xe5, 0x4b, 0x74, 0xbd, 0x91, 0x2a, 0xf7, 0xfb, 0x3d, 0x85, 0x2f, 0xa3, 0x6b, 0x50, 0x1f, 0x28,
	0x07, 0x9d, 0xbe, 0xfc, 0x65, 0x87, 0x2c, 0x48, 0x74, 0x02, 0xda, 0x04, 0x24, 0x8f, 0x54, 0x3a,
	0x3a, 0x52, 0xbb, 0x83, 0xa3, 0x61, 0xa7, 0x2f, 0xf7, 0x46, 0x7c, 0x85, 0xd0, 0x63, 0x44, 0xc2,
	0x5f, 0xa5, 0x45, 0x3c, 0x16, 0x91, 0xe5, 0xdf, 0xd0, 0xcf, 0xe9, 0xe8, 0x8c, 0xed, 0x7f, 0x41,
	0x7f, 0xd2, 0x8e, 0xb6, 0xdf, 0xb7, 0xa4, 0x38, 0xc7, 0xab, 0xe8, 0xbd, 0xaf, 0xc1, 0x46, 0x68,
	0x19, 0xaf, 0xf8, 0xff, 0xae, 0x40, 0x7a, 0x62, 0x46, 0x8d, 0xf4, 0xc4, 0x52, 0xe4, 0x54, 0xd7,
	0x90, 0xd2, 0x98, 0xa2, 0xa7, 0x3c, 0x16, 0x82, 0x5c, 0x22, 0x04, 0xe8, 0x3d, 0xbf, 0x57, 0xce,
	0x07, 0x3d, 0x6f, 0x8a, 0xae, 0x64, 0xab, 0xfc, 0x51, 0x68, 0xde, 0x51, 0x08, 0xa6, 0x25, 0x29,
	0xa2, 0x59, 0xc3, 0x8e, 0x41, 0xa2, 0x17, 0x2b, 0x06, 0x13, 0xb8, 0x14, 0x35, 0xff, 0x85, 0xa6,
	0xf9, 0x25, 0x0d, 0x25, 0xbe, 0x79, 0x23, 0xf7, 0x5d, 0x6f, 0x9a, 0x5a, 0x85, 0x52, 0x67, 0x7f,
	0x5f, 0x3d, 0x19, 0xf5, 0x14, 0x9e, 0x63, 0x9f, 0xe5, 0x61, 0xef, 0xb8, 0xc7, 0x08, 0x39, 0x71,
	0x8b, 0xb4, 0x42, 0x91, 0x50, 0x79, 0xb8, 0xf9, 0x7b, 0x61, 0xd1, 0xd6, 0xc5, 0xbb, 0xef, 0x87,
	0x11, 0xe8, 0xbc, 0x26, 0x65, 0xf0, 0x5d, 0x11, 0x3d, 0x7b, 0xa1, 0xae, 0x3c, 0x1f, 0x4c, 0xbd,
	0xd2, 0x35, 0x66, 0x35, 0xe5, 0x7b, 0x09, 0x24, 0x65, 0xeb, 0xc8, 0x02, 0x93, 0x92, 0x01, 0xa6,
	0xbb, 0x99, 0x9a, 0x96, 0xe2, 0x89, 0x74, 0x51, 0xd6, 0x0c, 0xdb, 0x9a, 0x6b, 0x05, 0x3b, 0x57,
	0x59, 0x01, 0x9f, 0x24, 0xeb, 0x2f, 0xab, 0xf1, 0xff, 0xd6, 0xc0, 0xee, 0xae, 0x07, 0xbb, 0x3a,
	0x54, 0x08, 0xec, 0xba, 0x4f, 0x3b, 0xc7, 0xc7, 0x14, 0x79, 0x08, 0x6a, 0x1e, 0xf2, 0x7c, 0x5a,
	0x4e, 0x6c, 0x90, 0xb3, 0x5a, 0x3c, 0xb4, 0x3e, 0xfe, 0x38, 0x78, 0xcd, 0x7f, 0xd9, 0xc7, 0x17,
	0x9e, 0xb1, 0x74, 0x3b, 0xef, 0x5b, 0xae, 0x31, 0xc6, 0xf1, 0x16, 0x65, 0xd1, 0x26, 0xdd, 0x81,
	0x0d, 0x13, 0x5f, 0x04, 0x13, 0x9a, 0xd0, 0xfd, 0x84, 0x52, 0x37, 0xa3, 0xaa, 0x50, 0x1b, 0x6e,
	0x9c, 0x6b, 0xce, 0x62, 0x9c, 0xe3, 0xcf, 0x4c, 0xd9, 0xcc, 0x57, 0xb9, 0x46, 0x5e, 0xc6, 0xc6,
	0x83, 0x24, 0xa9, 0xe1, 0xe9, 0x0f, 0x1b, 0x80, 0xc2, 0x34, 0x98, 0xfc, 0xa0, 0xb7, 0xa0, 0x1e,
	0x51, 0x6a, 0xe8, 0xb4, 0x9d, 0x28, 0x2b, 0xeb, 0x21, 0x75, 0xb2, 0x2e, 0xfe, 0x83, 0x83, 0xd7,
	0x7d, 0x1f, 0xfd, 0x6c, 0x60, 0x4d, 0x1f, 0xb9, 0x9a, 0x8b, 0xff, 0x67, 0x9c, 0x1c, 0xc3, 0x56,
	0xd0, 0x97, 0x8e, 0xb0, 0xeb, 0x1a, 0xe6, 0x64, 0x69, 0xa3, 0xdb, 0x82, 0x2a, 0x7d, 0xe1, 0x30,
	0x7e, 0x0f, 0xb2, 0x55, 0x29, 0xac, 0x83, 0x1e, 0x4f, 0xbc, 0x07, 0x51, 0x07, 0x21, 0xb9, 0x88,
	0xb7, 0x77, 0x67, 0x86, 0xf0, 0x85, 0x57, 0x19, 0x2f, 0x4a, 0xe2, 0xab, 0x5b, 0x44, 0x5b, 0x54,
	0x64, 0x8f, 0xb4, 0x0c, 0x0a, 0x2f, 0xbc, 0xc4, 0xe3, 0xc5, 0x60, 0xc5, 0x23, 0x5d, 0x65, 0x5e,
	0xfd, 0x27, 0x6e, 0x31, 0x5a, 0x59, 0x88, 0x79, 0xfe, 0x0f, 0x61, 0x3d, 0x6c, 0x83, 0xdf, 0xf8,
	0xdc, 0x95, 0xb2, 0x24, 0xc2, 0xd6, 0x79, 0xa5, 0xb8, 0x1a, 0xb2, 0xd1, 0x69, 0x1c, 0xc1, 0x46,
	0x82, 0x25, 0xa5, 0x14, 0x89, 0xd1, 0xb2, 0x16, 0xf5, 0x3a, 0x54, 0x98, 0x9e, 0x40, 0x83, 0x98,
	0xd2, 0x49, 0x77, 0xfb, 0x0a, 0x57, 0x9d, 0xe2, 0x5f, 0x38, 0xd8, 0x4e, 0x55, 0xe1, 0x85, 0x60,
	0x94, 0x1e, 0x02, 0x76, 0xeb, 0xd2, 0xf9, 0x76, 0x44, 0xe1, 0x0f, 0x1c, 0x9b, 0x77, 0x06, 0x1d,
	0x6e, 0x10, 0x81, 0x56, 0x64, 0x4f, 0xdf, 0x96, 0x52, 0xb9, 0xc2, 0x3b, 0x7a, 0x2c, 0x64, 0xb9,
	0xe7, 0xde, 0x0e, 0x27, 0x6e, 0xd0, 0x6e, 0x79, 0xfb, 0x04, 0xc0, 0xea, 0x51, 0xa7, 0xdf, 0x39,
	0x20, 0x27, 0x88, 0x12, 0x14, 0x3e, 0x19, 0xc8, 0x7d, 0x3e, 0x27, 0xfe, 0x2c, 0xcf, 0xae, 0x46,
	0xc2, 0x06, 0x04, 0x9d, 0x78, 0x16, 0x40, 0xc9, 0xab, 0xe0, 0xce, 0x89, 0x98, 0x53, 0x0a, 0x2e,
	0x9b, 0x90, 0x02, 0x75, 0x2a, 0xf5, 0x63, 0xcb, 0x30, 0xa9, 0xbd, 0x7e, 0xab, 0x71, 0x47, 0x4a,
	0x5f, 0x87, 0x06, 0xf0, 0x13, 0xcb, 0x30, 0x89, 0x1f, 0x5e, 0x66, 0x68, 0x7a, 0x03, 0x1a, 0xfa,
	0x02, 0x36, 0xa8, 0xce, 0xb1, 0x8d, 0xfd, 0x28, 0xf8, 0xcd, 0xc7, 0xbd, 0xe7, 0x69, 0xed, 0x52,
	0xfe, 0x90, 0x5e, 0x6a, 0x5a, 0x88, 0x4a, 0xb6, 0xe1, 0xe4, 0xf2, 0x2f, 0xb2, 0x0d, 0x37, 0xf6,
	0xe0, 0x7a, 0xda, 0x52, 0x2f, 0xa2, 0xa3, 0xfd, 0xfb, 0x55, 0xa8, 0x10, 0x25, 0x07, 0x36, 0xc6,
	0x2e, 0xb6, 0x91, 0x04, 0xf9, 0x09, 0x76, 0xd1, 0x46, 0xe2, 0x26, 0xbf, 0x81, 0x92, 0x17, 0xde,
	0xe2, 0x0a, 0x7a, 0x02, 0xe5, 0x09, 0x76, 0xd9, 0x75, 0x23, 0xda, 0x92, 0xd2, 0x2f, 0x6f, 0x1b,
	0x42, 0xd6, 0xa5, 0xa4, 0xb8, 0x82, 0x3a, 0x50, 0x9a, 0x60, 0xd6, 0x97, 0x22, 0x41, 0xca, 0x98,
	0x05, 0x37, 0x6e, 0x66, 0x0e, 0x5e, 0xc5, 0x15, 0x74, 0x1f, 0x56, 0x59, 0x7e, 0x50, 0x5d, 0x8a,
	0x5e, 0x6b, 0x35, 0x78, 0x29, 0x76, 0x3d, 0x23, 0xae, 0xa0, 0x0f, 0xa1, 0xc6, 0xd8, 0xfd, 0xbb,
	0x12, 0x74, 0x4d, 0x4a, 0x5e, 0xcb, 0x34, 0xae, 0xa7, 0x5d, 0xa7, 0x50, 0xf1, 0x92, 0xa6, 0xeb,
	0xcc, 0xe0, 0x4d, 0x29, 0x75, 0xc6, 0xd8, 0xd8, 0x92, 0xd2, 0x07, 0x85, 0xe2, 0x0a, 0xfa, 0x18,
	0x2a, 0x3a, 0x1d, 0xa9, 0x31, 0x0d, 0x37, 0xa5, 0xac, 0xb1, 0x5d, 0xa3, 0x21, 0x65, 0xce, 0xde,
	0x98, 0x17, 0x53, 0x4b, 0x37, 0x9e, 0x5d, 0xfa, 0x23, 0x32, 0xe6, 0x45, 0x6c, 0xe6, 0xc6, 0xbc,
	0x88, 0x4f, 0xd1, 0xc4, 0x15, 0x74, 0x00, 0x35, 0x07, 0xbb, 0xa1, 0x0a, 0x42, 0x82, 0x9f, 0xbe,
	0x85, 0x93, 0xe0, 0x67, 0xec, 0xbb, 0xe2, 0x0a, 0x7a, 0x0a, 0xf5, 0x49, 0x44, 0x51, 0x38, 0x8d,
	0xb1, 0x12, 0x1c, 0x4a, 0x63, 0xbc, 0x48, 0x8a, 0x2b, 0xe8, 0x33, 0x40, 0x13, 0xec, 0xc6, 0x8a,
	0x28, 0xda, 0x96, 0xb2, 0x4b, 0x7a, 0xe3, 0xd6, 0xf3, 0xea, 0xae, 0xb8, 0x82, 0xf6, 0x60, 0xdd,
	0x33, 0x8e, 0x5d, 0xaa, 0xa2, 0x4d, 0x29, 0xf5, 0x0a, 0xb7, 0xb1, 0x95, 0x71, 0xfb, 0x2a, 0xae,
	0xec, 0xc9, 0xb0, 0x39, 0xb6, 0xa6, 0x92, 0xe3, 0x48, 0x9a, 0xa9, 0xdb, 0x96, 0xa1, 0x4b, 0xe7,
	0x9a, 0xfd, 0x95, 0x34, 0x3b, 0xfd, 0xb2, 0x35, 0x31, 0x5c, 0xe9, 0xf4, 0xd2, 0xc5, 0xba, 0x64,
	0xd9, 0x93, 0x16, 0xc6, 0x2d, 0xf2, 0xa6, 0x65, 0x4c, 0xef, 0xd3, 0x3f, 0xdc, 0x9c, 0xce, 0x9f,
	0xb5, 0x8c, 0x29, 0xfd, 0xd9, 0xa2, 0xa7, 0xff, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x57, 0xab,
	0xf3, 0x23, 0x9f, 0x23, 0x00, 0x00,
}
