source 'http://gitlab.douyuios.com/douyu-ios/DouyuSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


#use_frameworks!

target 'ProtobufOnHttpTest’ do

pod 'CocoaLumberjack'
pod 'CocoaAsyncSocket'  
pod 'GCDWebServer', '~> 3.0'
pod 'Protobuf', '~> 3.5.0'

end