// Code generated by protoc-gen-go.
// source: reactions.proto
// DO NOT EDIT!

/*
Package reactions is a generated protocol buffer package.

It is generated from these files:
	reactions.proto

It has these top-level messages:
	PullReactionsRequest
	PullReactionsResponse
	PutReactionRequest
	PutReactionResponse
	DeleteReactionRequest
	DeleteReactionResponse
	PushReactions
*/
package reactions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entities "git.byted.org/ee/lark/im-protobuf/improto/entities"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 获取会话连续消息的Reaction
type PullReactionsRequest struct {
	MessageIds       []string `protobuf:"bytes,1,rep,name=message_ids,json=messageIds" json:"message_ids,omitempty"`
	FetchUsers       *bool    `protobuf:"varint,2,opt,name=fetch_users,json=fetchUsers,def=0" json:"fetch_users,omitempty"`
	FetchChatters    *bool    `protobuf:"varint,3,opt,name=fetch_chatters,json=fetchChatters,def=0" json:"fetch_chatters,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PullReactionsRequest) Reset()                    { *m = PullReactionsRequest{} }
func (m *PullReactionsRequest) String() string            { return proto.CompactTextString(m) }
func (*PullReactionsRequest) ProtoMessage()               {}
func (*PullReactionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_PullReactionsRequest_FetchUsers bool = false
const Default_PullReactionsRequest_FetchChatters bool = false

func (m *PullReactionsRequest) GetMessageIds() []string {
	if m != nil {
		return m.MessageIds
	}
	return nil
}

func (m *PullReactionsRequest) GetFetchUsers() bool {
	if m != nil && m.FetchUsers != nil {
		return *m.FetchUsers
	}
	return Default_PullReactionsRequest_FetchUsers
}

func (m *PullReactionsRequest) GetFetchChatters() bool {
	if m != nil && m.FetchChatters != nil {
		return *m.FetchChatters
	}
	return Default_PullReactionsRequest_FetchChatters
}

// 查询消息Reaction的返回数据类型
type PullReactionsResponse struct {
	MessageReactions []*entities.MessageReaction `protobuf:"bytes,1,rep,name=message_reactions,json=messageReactions" json:"message_reactions,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *PullReactionsResponse) Reset()                    { *m = PullReactionsResponse{} }
func (m *PullReactionsResponse) String() string            { return proto.CompactTextString(m) }
func (*PullReactionsResponse) ProtoMessage()               {}
func (*PullReactionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PullReactionsResponse) GetMessageReactions() []*entities.MessageReaction {
	if m != nil {
		return m.MessageReactions
	}
	return nil
}

// 添加Reaction请求
type PutReactionRequest struct {
	MessageId        *string `protobuf:"bytes,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	ReactionType     *string `protobuf:"bytes,2,opt,name=reaction_type,json=reactionType" json:"reaction_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PutReactionRequest) Reset()                    { *m = PutReactionRequest{} }
func (m *PutReactionRequest) String() string            { return proto.CompactTextString(m) }
func (*PutReactionRequest) ProtoMessage()               {}
func (*PutReactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutReactionRequest) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *PutReactionRequest) GetReactionType() string {
	if m != nil && m.ReactionType != nil {
		return *m.ReactionType
	}
	return ""
}

// 添加reaction返回值
type PutReactionResponse struct {
	Count            *int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutReactionResponse) Reset()                    { *m = PutReactionResponse{} }
func (m *PutReactionResponse) String() string            { return proto.CompactTextString(m) }
func (*PutReactionResponse) ProtoMessage()               {}
func (*PutReactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutReactionResponse) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 删除Reaction
type DeleteReactionRequest struct {
	MessageId        *string `protobuf:"bytes,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	ReactionType     *string `protobuf:"bytes,2,opt,name=reaction_type,json=reactionType" json:"reaction_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteReactionRequest) Reset()                    { *m = DeleteReactionRequest{} }
func (m *DeleteReactionRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteReactionRequest) ProtoMessage()               {}
func (*DeleteReactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteReactionRequest) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *DeleteReactionRequest) GetReactionType() string {
	if m != nil && m.ReactionType != nil {
		return *m.ReactionType
	}
	return ""
}

// Response
type DeleteReactionResponse struct {
	Count            *int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteReactionResponse) Reset()                    { *m = DeleteReactionResponse{} }
func (m *DeleteReactionResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteReactionResponse) ProtoMessage()               {}
func (*DeleteReactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteReactionResponse) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 推送Reaction更新信息到客户端
type PushReactions struct {
	MessageReactions   []*entities.MessageReaction                 `protobuf:"bytes,1,rep,name=message_reactions,json=messageReactions" json:"message_reactions,omitempty"`
	ReactionExtraInfos map[string]*PushReactions_ReactionExtraInfo `protobuf:"bytes,2,rep,name=reactionExtraInfos" json:"reactionExtraInfos,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized   []byte                                      `json:"-"`
}

func (m *PushReactions) Reset()                    { *m = PushReactions{} }
func (m *PushReactions) String() string            { return proto.CompactTextString(m) }
func (*PushReactions) ProtoMessage()               {}
func (*PushReactions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PushReactions) GetMessageReactions() []*entities.MessageReaction {
	if m != nil {
		return m.MessageReactions
	}
	return nil
}

func (m *PushReactions) GetReactionExtraInfos() map[string]*PushReactions_ReactionExtraInfo {
	if m != nil {
		return m.ReactionExtraInfos
	}
	return nil
}

type PushReactions_ReactionExtraInfo struct {
	IsCancelled       *bool            `protobuf:"varint,1,opt,name=is_cancelled,json=isCancelled" json:"is_cancelled,omitempty"`
	Notice            *entities.Notice `protobuf:"bytes,2,opt,name=notice" json:"notice,omitempty"`
	ReactionChatterId *string          `protobuf:"bytes,3,opt,name=reaction_chatter_id,json=reactionChatterId" json:"reaction_chatter_id,omitempty"`
	Type              *string          `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized  []byte           `json:"-"`
}

func (m *PushReactions_ReactionExtraInfo) Reset()         { *m = PushReactions_ReactionExtraInfo{} }
func (m *PushReactions_ReactionExtraInfo) String() string { return proto.CompactTextString(m) }
func (*PushReactions_ReactionExtraInfo) ProtoMessage()    {}
func (*PushReactions_ReactionExtraInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *PushReactions_ReactionExtraInfo) GetIsCancelled() bool {
	if m != nil && m.IsCancelled != nil {
		return *m.IsCancelled
	}
	return false
}

func (m *PushReactions_ReactionExtraInfo) GetNotice() *entities.Notice {
	if m != nil {
		return m.Notice
	}
	return nil
}

func (m *PushReactions_ReactionExtraInfo) GetReactionChatterId() string {
	if m != nil && m.ReactionChatterId != nil {
		return *m.ReactionChatterId
	}
	return ""
}

func (m *PushReactions_ReactionExtraInfo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*PullReactionsRequest)(nil), "PullReactionsRequest")
	proto.RegisterType((*PullReactionsResponse)(nil), "PullReactionsResponse")
	proto.RegisterType((*PutReactionRequest)(nil), "PutReactionRequest")
	proto.RegisterType((*PutReactionResponse)(nil), "PutReactionResponse")
	proto.RegisterType((*DeleteReactionRequest)(nil), "DeleteReactionRequest")
	proto.RegisterType((*DeleteReactionResponse)(nil), "DeleteReactionResponse")
	proto.RegisterType((*PushReactions)(nil), "PushReactions")
	proto.RegisterType((*PushReactions_ReactionExtraInfo)(nil), "PushReactions.ReactionExtraInfo")
}

func init() { proto.RegisterFile("reactions.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0xef, 0x8a, 0xd3, 0x4e,
	0x14, 0x6d, 0xb6, 0xed, 0xfe, 0xb6, 0xb7, 0xed, 0x6e, 0x3b, 0xfd, 0xb3, 0x25, 0xf0, 0x63, 0x6b,
	0x84, 0xa5, 0xa0, 0x4e, 0xa1, 0x0b, 0x22, 0x2b, 0x22, 0xb8, 0x2e, 0xd2, 0x0f, 0x2b, 0x65, 0xd0,
	0x45, 0xf4, 0x43, 0x49, 0x93, 0xdb, 0x76, 0xd8, 0x34, 0xa9, 0x99, 0x89, 0xd8, 0x87, 0xf0, 0x09,
	0x7c, 0x06, 0xdf, 0xc2, 0x07, 0x93, 0x4c, 0x32, 0x59, 0xbb, 0x8d, 0xfa, 0x41, 0xfc, 0x36, 0x73,
	0xcf, 0x99, 0x9b, 0x73, 0xcf, 0x9c, 0x0c, 0x1c, 0x85, 0x68, 0x3b, 0x92, 0x07, 0xbe, 0xa0, 0xeb,
	0x30, 0x90, 0x81, 0x79, 0x88, 0xbe, 0xe4, 0x92, 0x63, 0xba, 0xb7, 0xbe, 0x18, 0xd0, 0x9e, 0x44,
	0x9e, 0xc7, 0x34, 0x8f, 0xe1, 0xc7, 0x08, 0x85, 0x24, 0x27, 0x50, 0x5d, 0xa1, 0x10, 0xf6, 0x02,
	0xa7, 0xdc, 0x15, 0x3d, 0xa3, 0x5f, 0x1c, 0x54, 0x18, 0xa4, 0xa5, 0xb1, 0x2b, 0xc8, 0x29, 0x54,
	0xe7, 0x28, 0x9d, 0xe5, 0x34, 0x12, 0x18, 0x8a, 0xde, 0x5e, 0xdf, 0x18, 0x1c, 0x9c, 0x97, 0xe7,
	0xb6, 0x27, 0x90, 0x81, 0x42, 0xde, 0xc6, 0x00, 0x79, 0x08, 0x87, 0x09, 0xcf, 0x59, 0xda, 0x52,
	0xc6, 0xd4, 0xe2, 0xcf, 0xd4, 0xba, 0x02, 0x2f, 0x52, 0xcc, 0xba, 0x86, 0xce, 0x1d, 0x39, 0x62,
	0x1d, 0xf8, 0x02, 0xc9, 0x33, 0x68, 0x6a, 0x3d, 0xd9, 0x4c, 0x4a, 0x55, 0x75, 0xd4, 0xa0, 0x57,
	0x09, 0xa2, 0x4f, 0xb1, 0xc6, 0x6a, 0xbb, 0x20, 0xac, 0x77, 0x40, 0x26, 0x91, 0xcc, 0x08, 0xe9,
	0x90, 0xff, 0x03, 0xdc, 0x0e, 0xd9, 0x33, 0xfa, 0xc6, 0xa0, 0xc2, 0x2a, 0xd9, 0x8c, 0xe4, 0x3e,
	0xd4, 0xf5, 0xb7, 0xa6, 0x72, 0xb3, 0x46, 0x35, 0x64, 0x85, 0xd5, 0x74, 0xf1, 0xcd, 0x66, 0x8d,
	0xd6, 0x03, 0x68, 0x6d, 0x75, 0x4e, 0xf5, 0xb6, 0xa1, 0xec, 0x04, 0x91, 0x2f, 0x55, 0xd7, 0x32,
	0x4b, 0x36, 0xd6, 0x07, 0xe8, 0xbc, 0x44, 0x0f, 0x25, 0xfe, 0x0b, 0x25, 0x14, 0xba, 0x77, 0x9b,
	0xff, 0x56, 0xcc, 0xb7, 0x22, 0xd4, 0x27, 0x91, 0x58, 0x66, 0x2e, 0xfd, 0xa5, 0xc9, 0xe4, 0x1a,
	0x88, 0x3e, 0x76, 0xf9, 0x59, 0x86, 0xf6, 0xd8, 0x9f, 0x07, 0x71, 0x32, 0xe2, 0xf3, 0xa7, 0x74,
	0xeb, 0x53, 0x94, 0xed, 0x10, 0x2f, 0x7d, 0x19, 0x6e, 0x58, 0x4e, 0x07, 0xf3, 0xab, 0x01, 0xcd,
	0x1d, 0x3e, 0xb9, 0x07, 0x35, 0x2e, 0xa6, 0x8e, 0xed, 0x3b, 0xe8, 0x79, 0x98, 0x98, 0x76, 0xc0,
	0xaa, 0x5c, 0x5c, 0xe8, 0x12, 0x39, 0x81, 0x7d, 0x3f, 0x90, 0xdc, 0x49, 0xfc, 0xaa, 0x8e, 0xfe,
	0xa3, 0xaf, 0xd5, 0x96, 0xa5, 0x65, 0x42, 0xa1, 0x95, 0xf9, 0x9a, 0xe6, 0x33, 0xf6, 0xbf, 0xa8,
	0xdc, 0x6d, 0x6a, 0x28, 0x4d, 0xe7, 0xd8, 0x25, 0x04, 0x4a, 0xca, 0xfe, 0x92, 0x22, 0xa8, 0xb5,
	0xb9, 0x80, 0xe3, 0x5f, 0x0c, 0x43, 0x1a, 0x50, 0xbc, 0xc1, 0x4d, 0x7a, 0x9d, 0xf1, 0x92, 0x3c,
	0x86, 0xf2, 0x27, 0xdb, 0x8b, 0xb4, 0xa0, 0xfe, 0x9f, 0x5c, 0x61, 0x09, 0xfd, 0x7c, 0xef, 0x89,
	0x31, 0xfa, 0x6e, 0xc0, 0x91, 0x26, 0xbc, 0x0a, 0x11, 0x25, 0x86, 0xe4, 0x0c, 0x4a, 0x02, 0x7d,
	0x97, 0xb4, 0xe8, 0x6e, 0xbc, 0xcd, 0x36, 0xcd, 0x49, 0xa6, 0x55, 0x20, 0x4f, 0x61, 0xdf, 0x55,
	0x41, 0x21, 0x5d, 0x9a, 0x1b, 0x47, 0xf3, 0x98, 0xe6, 0x27, 0xc9, 0x2a, 0x90, 0xe7, 0x50, 0x5b,
	0xa0, 0xbc, 0xbd, 0xf4, 0x0e, 0xcd, 0x7b, 0x3f, 0xcc, 0x2e, 0xcd, 0xfd, 0x8f, 0xad, 0xc2, 0x8b,
	0x2b, 0xe8, 0x3a, 0xc1, 0x8a, 0x0a, 0x41, 0x6d, 0xdf, 0x0d, 0x03, 0xee, 0x52, 0xcf, 0x0e, 0x6f,
	0xe8, 0x7a, 0xf6, 0xfe, 0x6c, 0xc1, 0x25, 0x9d, 0x6d, 0x24, 0xba, 0x34, 0x08, 0x17, 0x43, 0xc4,
	0x61, 0x8c, 0x0c, 0xf9, 0xea, 0x91, 0x7a, 0xac, 0x66, 0xd1, 0x7c, 0xc8, 0x57, 0x6a, 0x39, 0xcc,
	0xe2, 0xf9, 0x23, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x02, 0x62, 0x79, 0xe3, 0x04, 0x00, 0x00,
}
